djcb/mu

mu4e/mu4e.texi

The function is expected to return plain text, not HTML.

Fix mistake in documentation

---

mu4e/mu4e.texi

The code and the prose were misplaced.

Fix configuration placement

---

mu4e/mu4e.texi

Emacs has line wrapping build in by default using `visual-line-mode`.
http://www.emacswiki.org/emacs/LongLines

Change `longlines-mode` for `visual-line-mode`

---

mu/mu-cmd-server.c

Hi.  I received some messages with spaces in the message id.  mu4e was having problems handling the messages when attempting the "move" server command to set flags when I viewed the messages.  The query to return all docids for the msgid was returning no results.  Surrounding the msgid with quotes in the mu query fixed the problem.
If this seems like the correct approach, feel free to merge the fix.  If you'd like to see it reworked in some way, I'd be happy to make another attempt.
Thanks for this amazing mailreader!

mu-cmd-server.c: quote msgid in query

---

mu4e/mu4e-vars.el

This variable has been replaced with mu4e-user-mail-address-list.
Signed-off-by: Alex Bennée <alex.bennee@linaro.org>

mu4e-vars: fix reference to obsolete mu4e-my-email-addresses

---

mu4e/mu4e-main.el

- The queue-related actions of `mu4e~main-view-real` have been extracted
to their own `mu4e~main-view-queue` method.
- The queue toggling action now has the word "currently" to easily.
distinguish between the current state and the toggle (e.g., "currently
queued" instead of just "queued").
- The "[f]lush queued emails" is only visible if there is at least 1
email in the queue.
- The number of emails in the queue is visible in the flushing
action (e.g., "[f]lush 10 queued emails").

Improve queue-related actions of the main view

---

mu4e/mu4e-main.el

Only whitespace changes.
In the absence of a particular section in the `HACKING` file, I chose to use the default elisp conventions. If you disagree, please tell me the rules so I can adapt `HACKING` and create a `.dir-locals` file.

Reindent source code to ease future modifications

---

mu4e/org-mu4e.el

When sending org mode mail, both the text/html and text/plain parts
contained the HTML version of the mail, instead of just the text/html
part. This patch puts the raw-body (org format) in the text part, and
the html with replaced images in the html part.

Fix org-mu4e bug with HTML in text/plain part

---

lib/mu-msg-crypto.c
lib/mu-msg-file.c
lib/mu-msg-part.c
lib/mu-msg-part.h
lib/mu-msg-priv.h

Since `parent` is not really used as a parent, I use it as the last
visited encrypted part while going down the parts-tree.
At the decryption of a part (`mu_msg_crypto_decrypt_part`) I check,
through the GMimeDecryptResult, for signatures (`check_decrypt_result`)
and add them to the part (`tag_with_sig_status`).  Any nested parts, hold
that encrypted part as their parent.  Finally at `handle_part`, for each
part I check if it a descendent of an encrypted part.  If so, I proceed
checking for signatures and adding them to the `msgpart`.

Fix for #280

---

mu4e/mu4e-headers.el

This solves the problem in issue https://github.com/djcb/mu/issues/215. There was an error everytime the message-view was not visible and the message-headers was not large enough to be splitted. I am trapping this error and opening message-view on the same window message-headers was (effectively replacing it, just like with mu4e-split-view set to anything but 'horizontal' or 'vertical').

mu4e: avoid error when splitting headers window

---

mu4e/mu4e-actions.el

add " " between :EMAIL: and 'mail' because org-contacts needs the separator.
move the cursor to the left of 'name'

* mu4e/mu4e-actions.el: modify org-capture-templates

---

mu4e/mu4e-compose.el

When `message-kill-buffer-on-exit` was set to nil mu4e would not close
the new frame.  Closing the new frame should be independent of killing
the buffer.  This patch corrects this.
(relates to #615)

Make `mu4e-compose-in-new-frame` always kill frame

---

lib/mu-msg-iter.cc

The core dump only seems to occur if mu4e-headers-include-related is
set to t.
Apparently, std::string's c_str() method is confusing to many
people (including me), c.f.
http://stackoverflow.com/questions/22330250/how-to-return-a-stdstring-c-str
http://stackoverflow.com/questions/23464504/string-and-const-char-and-c-str
The answer seems to be that the pointer c_str() returns may not be
valid past the current statement; returning it, or even using it
subsequently can have you sending a wild pointer into e.g. g_strdup().
In short, it seems idioms like this are okay:
return g_strcmp0 (s1.c_str(), s2.c_str()) < 0;
Whereas idioms like this are not:
const char *msgid (iter->msgid().c_str());
return msgid ? g_strdup (msgid) : NULL;
At least in my environment by the time we get to g_strdup() the …

Fix call to c_str() that sometimes dumps core on OpenBSD i386-current

---

mu4e/mu4e.texi

I've hopefully made it clear that the BBDB setup should come after `(require 'mu4e)`.

Follow-up to commit #630: Clarify bbdb setup comes after mu4e setup

---

mu4e/mu4e-headers.el
mu4e/mu4e-vars.el

mu4e-use-fancy-chars to can have the setting t (use fancy chars for marks and threads), marks, threads or nil. The change won't brake any config.

Make usage of fancy chars configurable.

---

mu4e/mu4e-draft.el

Hello,
I noticed that I don't have a User-agent header in my mails. With this change, it shows up in my outgoing mails.

* mu4e-draft.el: fix adding User-agent header

---

mu4e/mu4e-headers.el
mu4e/mu4e-vars.el

Fix typo from higl.* to highl.*

---

lib/tests/test-mu-str.c

glib 2.46 complains if this isn't the case:
(test-mu-str:28790): GLib-ERROR **: duplicate test case path: /mu-str/mu-str-esc-to-list

Ensure tests have unique names.

---

mu4e/mu4e-draft.el
mu4e/mu4e-headers.el
mu4e/mu4e-view.el

The byte-compiler also complains about `mu4e-doc-dir` not being defined. I have not fixed that because I don't know if that variable is defined and set in a generated file. If so, you should add `(defvar mu4e-doc-dir)` to silence the compiler.
I have also noticed that you still use `cl` instead of `cl-lib` and that indentation often is very broken. Would you accept patches that fix those things?

Fix issues reported by the byte-compiler.

---

mu4e/mu4e-view.el

* mu4e/mu4e-view.el (mu4e-view-message-text):
When using `propertize' all properties added by `mu4e-html2text-command'
in html message are overwrited by `mu4e-view-body-face', so use here
`add-face-text-property' if available, otherwise behave as before and return
body unchanged.

Fix propertizing body with mu4e-view-body-face.

---

man/mu-easy.1

This option has apparently changed somewhere down the line.

docs: mu-easy: summary to summary-len

---

mu4e/mu4e-lists.el
mu4e/mu4e-utils.el
mu4e/mu4e.texi

This way mu4e will intelligently shorten mailing list names which
contain dots:
(setq mu4e-mailing-list-patterns
'("\\([a-z0-9.]+\\)\.lists\.company\.com"))

Allow specifying list shortnames with regexes

---

mu4e/mu4e.texi

Dashes are pretty common in mailing list names.

Include '-' in example regex

---

man/mu-find.1

This is a long-standing feature, it works, but there was no mention of
it in the docs.
There's also bodyhtml:* but that doesn't seem to do anything for me,
maybe I just don't have enough HTML mail.
These also exist:
path,l          ???
refs,r          ???
But I don't know what they're for. They should probably be documented
too.

mu-find(1): Document that you can search throug body:*

---

mu4e/mu4e-headers.el

mu4e: Moving in headers should only change view if mu4e-split-view is non-nil.

---

mu4e/mu4e-headers.el
mu4e/mu4e-view.el

Because this was a lambda C-h m would just show "??" instead of the
function name, and the documentation would be really confusing since it
showed the deparsed lambda function instead of the function name being
called.
Fix this by refactoring both the view & headers [ and ] functions into
named functions, and make their shared logic new internal
mu4u~{headers,view}-* functions.

mu4e-{view,headers}: Refactor a (lamba) kbd-bound function into a named function

---

man/mu-server.1

This 500 number was correct in v0.9.7-pre-302-g858552a, but since
v0.9.8.2-41-gc2e3eac it's been hardcoded to 1000 in the server code.
See also issue #715 and issue #716.

mu-server man page: Correct documentation about status reporting

---

mu4e/mu4e-mark.el

The mu4e-use-fancy-chars customization wasn't supported for the headers view's main marking of messages. Now it is, I've bent over backwards here to not make this break anyone's existing customization at the expense of some slight complexity.
I just added non-ASCII fancy characters for two of the actions, I couldn't find topical ones for the rest.

Add support for mu4e-use-fancy-chars to the marking in the headers view

---

mu4e/mu4e.texi

Extends the contexts' example to be more functional. It sets a default context to be used and sets `mu4e-user-mail-address-list` to reflect the e-mail addresses in the different contexts.

Extend contexts example

---

lib/mu-store.cc

Doing:
!access(...) == 0
Is equivalent to:
(!access(...)) == 0
Not:
!(access(...) == 0)
And throws this warning under clang:
mu-store.cc:77:6: warning: logical not is only applied to the left hand
side of this comparison [-Wlogical-not-parentheses]
if (!access(xpath, F_OK) == 0) {
^                    ~~
mu-store.cc:77:6: note: add parentheses after the '!' to evaluate the
comparison first
if (!access(xpath, F_OK) == 0) {
^
(                       )
mu-store.cc:77:6: note: add parentheses around left hand side expression
to silence this warning
if (!access(xpath, F_OK) == 0) {
^
(                   )
It ends up doing what the author intended anyway since access() returns
-1 on error, and !-1 == 0, but just do the more obvious check and check
that we don't get 0 here with !=.

mu-store: Silence confusing code that's throwing a clang warning

---

mu4e/mu4e.texi

Let's not spam the poor sods who own foo.com and bar.com, or home.com
etc. Went through the various examples and changed them to use
example.com or subdomains of example.com where appropriate, even when
the domain or TLD didn't exist (yet!) for completeness.
See-Also: https://tools.ietf.org/html/rfc2606

Don't use real (or potentially real) domains in examples

---

mu4e/mu4e-headers.el

As discussed in #730, this adds two lists of functions (I'll make them into defcustoms, with proper documentation, if we settle on this implementation) which are applied in sequence to produce the headers line.
* `mu4e~headers-field-handler-functions` are applied one by one to produce each header field.
* `mu4e~headers-line-handler-functions`  are applied one by one to produce the full header line.
This could allow users to display the Unicode status icons in a different font, or to make display the subject line in a variable-pitch font, or to color specific recipients differently, or to add a background to every odd column, and so on.
Similarly, with an implementation of a line handling function that keeps one bit of state, we could have a zebra pattern on lines (though this leads me to …

Initial implementation of customizable headers

---

mu4e/mu4e-context.el

The documentation of `mu4e-context-determine` states that
>If there are contexts but none match, return nil, unless PICK-FIRST is non-nil, in which case return the first context."
but it never actually checks `pick-first`.

Fix mu4e-context-determine to match documentation

---

mu4e/mu4e-compose.el
mu4e/mu4e-context.el

When `mu4e-context-determine` fails to pick a context (i.e. returns nil) when invoked from `mu4e~compose-handler` and there are available contexts, prompt the user to pick one.
This PR depends on #737, so please review/pull that one first.

When mu4e-context-determine fails, prompt user

---

mu4e/mu4e.el

I was try `package-install-file` with the path mu4e in my site-lisp in `/usr/local`. I got the following error:
<pre>Debugger entered--Lisp error: (error "Package lacks a file header")
signal(error ("Package lacks a file header"))
error("Package lacks a file header")
package-buffer-info()
package-install-from-buffer()
package-install-file("/usr/local/Cellar/mu/HEAD/share/emacs/site-lisp/mu/mu4e/mu4e.el")
funcall-interactively(package-install-file "/usr/local/Cellar/mu/HEAD/share/emacs/site-lisp/mu/mu4e/mu4e.el")
call-interactively(package-install-file record nil)</pre>
Then I dug a little bit. I found [Conventional Headers for Emacs Libraries](http://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html)
I found some slight differences. Here it is.
It really doesn't make …

comform emacs libs convention

---

lib/mu-msg-sexp.c

I had a bug where mu4e wouldn't display a message, and instead kept "Waiting for message..." in the buffer. It was a bit annoying to debug because of the async nature of mu4e and because of an `ignore-errors` in `mu4e~proc-eat-sexp-from-buf`. The problem was that mu didn't properly quote some backslashes (in the mail, the name of the attachments had backslashes!), causing `read-from-string` to produce an error, which was ignored because of `ignore-errors`. This PR is a potential fix but I'm not sure it's the right place to do the escaping. Of course feel free to ignore and fix by other means.
[makes me wonder if `mu4e~proc-eat-sexp-from-buf` should perhaps be a tiny bit smarter about which error to ignore...]

mu: escape the name of the part

---

mu4e/mu4e-headers.el

Prevent stray % in queries to be interpreted by the modeline formatting.

mu4e: escape % in queries when updating the mode-string

---

mu4e/mu4e-headers.el

I'm using this for a rather nasty hack. When I open different bookmarks
in the mu4e-main view I want to set options for them, currently just
tweaking:
* mu4e-headers-show-threads
* mu4e-headers-include-related
* mu4e-headers-skip-duplicates
* mu4e-headers-results-limit
This is because some of my searches are *really* expensive when I
include related threads (huge batches of cron-generated E-Mails), but
some aren't. I couldn't find another way to do this. Using
mu4e-headers-mode-hook doesn't work, because we don't have access to the
search (just a variable showing the last search).
Also maybe we should be passing the actual key chord for the bookmark
here. I don't care since I look up the search string that'll be executed
and go from there, but maybe that interface would make more sense. …

mu4e-headers: Add hook executed when we're opening bookmarks

---

NEWS.org
mu4e/mu4e-headers.el

This was merged in as part of pull request #718 but changed to a more
general facility in 7716e00.
It's fantastic that we have the more general hook facility for any
search, but the primary use-case I had for the bookmark hook can't be
satisfied by the more general mu4e-headers-search-pre-hook.
The reason I added this hook was to emulate the folders I used in
Icedove as mu4e bookmarks. E.g. some folders are threaded, others are
not. By default mu4e only allows you to set this globally via options
like mu4e-headers-show-threads.
So I have a mu4e-headers-search-bookmark-hook which is basically a long
line of cond statements like:
((string-equal expr "NOT flag:trashed AND date:365d..now AND (flag:flagged)")
(setq mu4e-headers-show-threads nil)
(setq mu4e-headers-include-related nil)
(setq …

mu4e-headers: Add hook executed when we're opening bookmarks (again)

---

mu4e/mu4e-utils.el
mu4e/mu4e-vars.el
mu4e/mu4e.texi

Give users choice to decide if they want to run automatic mu4e-index-update in background or not

mu4e: add mu4e-index-update-in-background

---

mu4e/mu4e-draft.el

If user-full-name is set to this format: ```Last Name, First Name```, without proper quotation, SMTP will use ```Last Name``` for from field which is wrong.

mu4e: quote user-full-name according to rfc822 when construct from field

---

guile/mu.scm

In commit 8e3fbe380ec0 mu:get-parts was renamed to mu:c:get-parts but
get-parts method was not updated. Fix it.

Update calls to mu:get-parts after name change

---

mu4e/mu4e-contrib.el

In `mu4e-contrib` there were spam-filtering functions suitable for the `headers` mode but not for the `view` mode.  This alleviate this asymmetry...

Add spam-filtering functions suitable for the view mode

---

mu4e/mu4e.texi

Fixing the small typo which caused cosmetic errors in the Editor View Section.

Fix minor typo on line 1486

---

.gitignore

Currently the whole directory "/mu" are ignored, thus we have to force git to track the files in that directory.

Only ignore the "/mu/mu" executable

---

mu4e/mu4e-compose.el
mu4e/mu4e.texi

The default is expressed by the variable `mu4e-compose-format-flowed`, so it is easy to change.  However, given the variety of devices people use to read mails, I've considered that a format that respect that is better (however some important services — gmail, github — do not understand format=flowed so maybe we want the "long lines" mode to be the default).

Compose mails with format=flowed by default

---

mu4e/mu4e-compose.el

Without this menu entry, one has to remember the command name which is
not convenient.  This entry also helps to discover the "capture" feature.

Add a menu entry to attach captured messages

---

mu4e/org-mu4e.el

For users don't have latex installed but still want to use org-mu4e-compose-org-mode

mu4e: Make dvipng optional when convert from org to html

---

mu4e/mu4e-actions.el

This patch improves the behavior of mu4e-action-show-thread.  This
action now leaves the point on the message where the action was invoked,
which helps prevent losing ones' place in a long thread.  When invoked
in view mode, it continues to display the message that was being viewed,
instead of returning to a header-only view.

Improve behavior of mu4e-action-show-thread

---

mu4e/mu4e-draft.el

Hi Dirk,
I was wondering why threading in `mu` suddenly stopped working sporadically since about 2 weeks ago… so after some bisecting, here it the fix. Basically, the “References” header have been erroneously dropped for all messages composed with less than `mu4e~max-reference-num` number of reference.
I guess there are really [too many parenthesis](https://xkcd.com/297/) in lisp :p
Arthur

[FIX] references header dropped bug

---

mu4e/mu4e-utils.el

The mbsync command uses carriage return characters to go to the beginning of the line.  This change does the same for the mu4e-update buffer.  See also #827.

Handle mbsync output in mu4e-update buffer

---

guile/scripts/find-dups.scm

(mu:for-each-message ...) allows an optional expression to be passed
so that only messages matching that expression are searched when
looking for duplicates.
This patch adds a --expr flag so that e.g.
find-dups.scm --expr d:6m..3m
will reduce the range of messages to those between 3 and 6 months ago
to search for duplicates.  I found this useful when using expressions
to find messages in a particular year, rather than searching the whole
database.  This is often quicker and less worrying than searching the
whole database.
If --expr is not provided, expr should default to #t so that the whole
database is searched as before.

Add --expr flag to constrain search when looking for duplicates

---

mu4e/mu4e-actions.el

The mu4e-message-field function was called in a way that would never
work, fix that by calling it correctly.
There's the additional follow-up TODO here that the mu4e-message-field
function itself should probably die on this sort of invocation, but I
don't know enough about elisp idioms to know how that should look.
This fixes my issue #894.

Fix a regression in pull request #831

---

mu4e/mu4e-actions.el

This contains 2 fixes. An update from the previous pull request #845 and a fix to drafting of messages which explains why some of my "related messages" started disappearing.

mu4e-actions: improve mbox handling for multiple marks

---

mu4e/mu4e-compose.el
mu4e/mu4e-context.el
mu4e/mu4e-vars.el

When the background is dark, the mode-line background may not be.  That means that the default color chosen to display the context (`mu4e-title-face`) may not be the best one (and may not be easily customizable because it is tied to the way titles are displayed on dark background).  This PR adds a new color for the context (initialized with the old face so nothing changes by default).

Add a face for displaying the context in the mode-line

---

mu4e/mu4e-view.el

Suggested by Christophe from https://github.com/djcb/mu/commit/250793317669f415385623082cf91d35c28c16f5#commitcomment-18804074

mu4e: show '...' when header field folded and keep text-properties

---

mu4e/mu4e-utils.el
mu4e/mu4e-vars.el

The local part of email addresses is supposed to be case sensitive according to the standard but this is typically not respected (for good reasons).  The domain part, on the other hand, should be matched case insensitively.
This PR takes the stand that the whole address should be matched case insensitively because this is the common practice.

Compare email addresses case insensitively

---

mu4e/mu4e-headers.el
mu4e/mu4e-utils.el

This PR is to add a hook that will be ran when users update and delete a message and `mu4e-index-updated-hook` invoked.
I'm using https://github.com/agpchil/mu4e-maildirs-extension to show maildirs summary and it currently uses `mu4e-index-updated-hook` to detect there is a change in db. It is not reliable for this use case. E.g. if I read/delete couple of messages in headers view and go back to main view, it doesn't know there are some changes that need to recalculate the summary.

mu4e: add mu4e-msg-changed-hook

---

mu4e/mu4e-message.el

Hi,
Emacs already has the function ``shr-render-region`` which requires Emacs been built with ``libxml2`` option.  This built-in function also reports better error message if the ``libxml2`` option was disabled.
Also some minor space fixes.
Please note, for unknown reason, Github does **NOT** show my changes correctly.   Please ``diff`` by yourself.  Thanks!
Cheers,
Aly

mu4e: use builtin function "shr-render-region" for simplicity

---

configure.ac

The version under development is now 26. I installed Emacs from source
via Git recently, it gives:
emacs-version
=> "26.0.50.2"

Support Emacs 26 in configure.ac

---

lib/mu-query.cc
mu/tests/test-mu-query.c

The old behaviour would compare the strings, so would swap the start and end ranges if start was 3K and end was 2M.
Fixes: #964

mu: swap begin and end if begin is _numerically_ bigger than end

---

mu4e/mu4e-compose.el

org-mime and potentially other users of `compose-mail' pass a parameter
`other-headers', an alist of the form ((symbol . string)).
`mu4e~compose-mail' sends this parameter to message-add-header, which
appears to expect a string instead.  We therefore loop through
other-headers and instead pass a string to message-add-header for each
element of other-headers.

force use of strings for other-header in mu4e~compose-mail

---

mu4e/mu4e-headers.el

`mu4e-msg-changed-hook` should add to `mu4e-index-updated-hook` globally instead of header mode only. Otherwise, it causes issue like https://github.com/agpchil/mu4e-maildirs-extension/issues/34

mu4e: add mu4e-msg-changed-hook to mu4e-index-updated-hook globally

---

mu4e/TODO
mu4e/mu4e-compose.el
mu4e/mu4e-draft.el
mu4e/mu4e-vars.el
mu4e/mu4e.texi

This commit adds a global variable `mu4e-compose-forward-as-attachment`. To enable choosing forwarding method on a per-message basis would probably require either:
* changing the mu server backend so that it distinguishes between inline forwarding and forwarding as attachment;
* changing the mu server backend so that it doesn’t return attachments at all and making both inline and as attachment forwarding via MIME (and also making mu4e actually display MIME-enclosed inline emails).

mu4e: Add possibility to forward messages as attachments

---

mu4e/mu4e-compose.el

electric-quote-(local-)mode used to have no effect because
`comment-use-syntax' was left to `undecided' so the electric mode was
not enabled for paragraphs.
Fixes https://github.com/djcb/mu/issues/997

Make electric-quote-(local-)mode work when composing emails

---

lib/mu-msg-sexp.c
lib/mu-msg.c
lib/mu-msg.h
lib/tests/test-mu-msg.c
mu4e/mu4e-message.el

This is my initial attempt at addressing #808, supporting `format=flowed` (and `delsp=yes`) when viewing mail.
While this does rewrap some test messages I've tried nicely, I wouldn't recommend merging it in its current form:
- ~There are almost certainly may be memory leaks here.~ Update: may not be true any more, after the last few commits on this branch.
- ~I also encountered a situation where some mails didn't load.~ Update: I was able to track down why, and plugged that particular hole. It's running fine for me now.
- I suspect we would also want a toggle to say whether to honour reflow, much as we do for sending.
I fear this approach is too simplistic because of the way mu accumulates plain-text bodies. This approach could produce very nasty results if some plain-text bodies are …

POC: Respect format=flowed and delsp=yes for viewing plain-text messages

---

mu4e/mu4e-headers.el

When the frame running mu4e is in another virtual desktop or iconified, but
still contains a visible headers buffer, do not attempt to create a new view.

Do not duplicate headers views in iconified/hidden frames

---

NEWS.org
lib/mu-util.c
lib/mu-util.h
man/mu.1
man/mug.1

When you have multiple mu home directories, e.g. for the use case
detailed in my "Changing mu4e-{maildir,mu-home} from a context hook"
post to the mailing list it's quite inconvenient to have to hammer out
"mu --muhome=.. find .." every time you want to run some ad-hoc
command.
This allows me to set up a screen session where I do searches in mu
directory A in some screen panes, and searches in directory B in
others.
I initially called this MU_MUHOME but then I noticed that the perl
plugin has MUP_MU_HOME for analogous functionality, so I'm just
following its example.
The code I'm adding in mu-util.c is just a copy/paste & adjustment of
the same sort of already tested functionality in
mu_util_guess_maildir() just a few lines earlier.

Add support for specifying --muhome via MU_HOME in the environment

---

perl/.gitignore

These get created by ExtUtils::MakeMaker, so they won't be found by
grepping our own code, but they're created by the build process.

perl: Add a .gitignore file with the MYMETA build assets

---

mu4e/mu4e-draft.el
mu4e/mu4e-vars.el

Introduce a new variable, mu4e-compose-reply-ignore-address, which matches addresses to be skipped when doing wide replies.
This is identical in behavior to messages-dont-reply-to-names from message.el (which we default on). See RFE #915.
In fact, since it supports the same values, I would be tempted to ``defalias`` instead of ``defcustom``, or use ``message-dont-reply-to-names`` directly. But I'm flexible here. An alternative would be to default to mu4e-compose-complete-ignore-address-regexp.
This finally fixes the ability to perform wide replies with noreply addresses. For instance, when replying to github issues with a "\\bnoreply\\n" regexp, mu4e will not even prompt for a wide reply anymore, since all Cc: addresses get removed (as they should).
Feedback appreciated.

Allow to ignore addresses when doing wide replies

---

mu4e/mu4e-headers.el

The variable mu4e-headers-advance-after-mark can be set to nil if you
want to disable moving to the next mail after marking.

mu4e: advance after mark can now be disabled

---

mu4e/mu4e-headers.el

Even though the user may be editing this expression there is no reason
to not have the mu4e~headers-search-hist present for the prompt. Emacs
will only replace it with system wide history which would likely
contain irrelevant history for the action.

mu4e: don't loose search history when editing search

---

mu4e/mu4e.texi

Quotation from the commit log:
> offlineimap/Changelog.md says Gmail `realdelete' option is considered
> harmful and was removed on OfflineIMAP v6.5.2.1 (2012-04-04).
so we should remove it.
See: https://github.com/OfflineIMAP/offlineimap/blob/master/Changelog.md#offlineimap-v6521-2012-04-04

mu4e: remove `realdelete' option of OfflineIMAP

---

mu4e/mu4e-draft.el

When trying to send an email with no body, `message-narrow-to-headers` can't find the `mail-header-separator` because it isn't followed by a newline. In that case, the narrowed region falls back to everything until `(point-max)`, which includes the `"--text follows this line--"` string. In turn, when the `message-send-mail` function populates the required headers, these are added *after* the  `"--text follows this line--"` string. 
Example output:
```
User-agent: mu4e 0.9.16; emacs 24.5.1
From: foo@foo.net
To: bar@bar.net
Subject: baz EOM
--text follows this line--Fcc: /path/to/foo
Date: Sat, 11 Mar 2017 22:27:11 -0800
Message-ID: <878tobau2o.fsf@foo.net>
```

mu4e: fix sending emails with no body

---

mu4e/mu4e-headers.el
mu4e/mu4e-vars.el

Just add an indicator "(updating)" in the modeline when an update is running. 
It is disabled by default and can be enabled through the custom variable `mu4e-display-update-status-in-modeline`.
I use auto update in the background when displaying the mails of my inbox (to be sure to see the last messages).
It can be annoying to be unable to know when it's done.

Add info on update status in modeline

---

mu4e/mu4e-compose.el

Depending on whether the original email was encrypted, one can set
different reply policies.
This fixes an issue raised in issue #865, when `mu4e-compose-crypto-reply-policy` conflicted with sign-by-default. Now, two variables replace the old `mu4e-compose-crypto-reply-policy`:
- mu4e-compose-crypto-reply-encrypted-policy
- mu4e-compose-crypto-reply-plain-policy
I'd be very happy to make any adjustment.

Allow to set the reply policy in a smart manner

---

mu4e/mu4e-view.el

* mu4e/mu4e-view.el (mu4e-view): Do it.
In `mu4e-view` `mu4e-view-mode` run before any text is inserted, as a result all functions from 
`mu4e-view-mode-hook` modifying text in message have no effect.

Ensure mu4e-view-mode-hook run after text insertion

---

mu4e/mu4e-headers.el

The little bug was caused by a little confusion of the key for list-IDs.
Namely, we use `:list` and not `:list-id` for list-IDs.

mu4e: fix bug preventing mu4e-headers-change-sorting to sort by list

---

configure.ac

The value in configure.ac is out of sync with the git tags.

Bump version string to 1.0-alpha3

---

mu4e/mu4e-vars.el

This is just a tiny fix for doc strings that confused me when I was looking for the function `mu4e-message-field`.

mu4e/mu4e-vars.el: replace references to mu4e-message-get-field

---

mu4e/mu4e-view.el
mu4e/mu4e.texi

The default was to use e to save one attachment or C-u e to save multiple. This
simplifies it so that e simply offers to save one or many attachments.

mu4e: simplify what "e" does in mu4e-view mode

---

mu4e/mu4e-compose.el

offlineimap will only sync directories that have 'cur', 'tmp', and
'new' sub-directories. Currently, mu4e can end up in a state where the
sent folder only has the 'cur' directory and is therefore not synced.
Upon saving a sent email, emacs' write-file will prompt to create
parent directories if the sent maildir does not already exist. This
results in the following directory structure:
`<mu4e-maildir>/<sent>/cur/<email>`
Note that the 'tmp' and 'new' directories are missing. This commit
ensures that they are always created.

mu4e: ensure sent dir is created with proper maildir structure

---

mu4e/mu4e-about.org

It appears that these need to be on the same line for Emacs to render the link correctly.

Fix display of bugs link in mu4e-about.org

---

configure.ac
mu4e/mu4e.texi
mu4e/texi.texi.in

Automake contains some support for automagically adding version information to a texi manual (see
https://www.gnu.org/software/automake/manual/automake.html#Texinfo).
> If the .texi file @includes version.texi, then that file will be automatically generated
This patch gets rid of the texi.texi.in and instead uses the standard method to inject version information in the manual.
This fixes https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=870634

Use automake support for texi to generate version info in the manual

---

mu4e/mu4e.texi

External links are updated to point to the most informative pages. Pure
http links are upgraded to https were possible.
The only broken link is the one for *org-contacts*. I wasn't able to find a current page for that project.

mu4e.texi: Fix and update external links

---

mu4e/mu4e-message.el

html2text is deprecated in the emacs pretest, by unconditionally
importing it mu4e causes a mildly irritating yes/no prompt to appear
during startup.
This change ensures that html2text is not loaded unless the emacs
running is a version that does not have 'shr-insert-document

Only require html2text if it will be used

---

mu4e/mu4e-speedbar.el

Instead use the aliased variable `dframe-with-attached-buffer`.
The alias was established in Emacs 24.4.

No longer use obsolete alias speedbar-with-attached-buffer

---

mu4e/mu4e-utils.el

mu4e~fontify-signature had been coloring the first signature of a digest message and all the subsequent messages after the first signature.  I altered the code so it colors each signature and stops at the RFC 1153 border of 30 (or more) hyphens.
I experimented with another version that stopped coloring if it detected a quoted message, new headers, or another signature, but I think in all these cases the composer of the message has put their signature in front of the old content in error.  Since I can't predict what sorts of things people would want to put in their signature and RFC 3676 doesn't specify any way to signal the end of a signature, I stuck with the RFC 1153 definition.
Respectfully submitted,
-James

updated fontify-signature for RFC 1153 compliant digest messages

---

mu4e/mu4e-utils.el
mu4e/mu4e-vars.el

This is a fix to limit the length of the query string displayed in the `spaceline` modeline.
The `spaceline` package displays the query in a segment of the modeline. When this is a long (perhaps bookmarked) query, the modeline either (a) becomes crowded or (b) another problem manifests where the whole spaceline modeline goes blank.
The variable `mu4e-modeline-max-width` is introduced to limit the length and `mu4e~quote-for-modeline` is extended a bit to shorten the query string if needed.

shorten modeline str if longer than max-width

---

mu4e/mu4e-headers.el

Use special prefixes for orphan threads as suggested by @wavexx. It should look like:
```
Unrelated message
─>Single orphan message
┬>Orphan messsage
├>Second message on orphan thread
└>Last message on orphan thread
```

Mu4e orphan thread prefix

---

mu4e/mu4e-compose.el

Missing the quote makes `nil` obsolete instead of `mu4e-compose-crypto-reply-policy`.

Fix call to make-obsolete-variable

---

mu4e/mu4e-mark.el

This a pull request to improve the region bounds checking when marking headers so that too many headers are not marked when a region is active.
For example, using evil I visually select the lines for two emails:
At this point, if I were press 'd' to mark these two emails for delete, then the third email from 'NETGEAR' would be marked for deletion as well.
I've tracked this down to the fact that `(region-end)` is not actually included in the region, so while the region only extends to the end of the second line, mu4e actually thinks it extends to the first position on the third line.
You can verify that `(region-end)` is outside the actual region by putting the cursor on the last character in a word, running `(point)`, then selecting that word, running `(region-end)`, and you'll notice …

Fix region bounds checking when marking headers in mu4e

---

mu4e/org-mu4e.el

This allows to defer loading mu4e. That is, if we simply put in our
init file:
```
(with-eval-after-load 'org
(require 'org-mu4e))
```
then mu4e is only loaded if either we follow a mu4e link from an org
buffer or we call the autoloaded function `mu4e` to read our emails.
Storing org-mode links from mu4e buffers is unaffected by this change
since `org-mu4e-store-link` only applies from mu4e buffers.
Regarding the second, experimental part of org-mu4e.el about editing
mails with org-mode, I am not completely sure but I think it should
also be unaffected since it also seems to only apply from mu4e buffers.

org-mu4e: move mu4e requirement inside org-mu4e-open

---

mu4e/mu4e-actions.el

When in single-window mode and invoking `mu4e-action-show-thread` from
the view buffer, stay in the headers buffer rather than going back to
the view buffer.

mu4e: fix action to show thread for single-window mode

---

mu4e/org-mu4e.el

#920 fix links in Org 9 (Related discussion: #947). At the same time, `org-mu4e-store-and-capture` is still using `org-mu4e-store-link` only, so it doesn't work in Org 9. Fix by interactively calling `org-store-link` instead.

org-mu4e: fix org-mu4e-store-and-capture for Org 9.0

---

mu4e/mu4e-utils.el
mu4e/mu4e.texi

This allows one to dynamically generate the query string, based for example on the value of a variable.
I added an example in the manual, but actually my real motivation is the following feature.
I'm subscribed to a bunch of mailing lists and they're quite noisy. So I don't want to see them in my standard unread bookmark. Because I don't want to hardcode this list of mailing lists to exclude, I store them in a variable.
I have a header view action to add the current message's mailing list to that variable.
And I have another bookmark that shows the unread messages for only one list, by asking me what list I want to look at.
```elisp
(defcustom ibizaman/mu4e-unread-excluded-lists nil
"Mailing lists to be excluded from default unread view."
:group 'mu4e
:type '(repeat string))
(defun …
```

mu4e: allow :query to accept a function returning a query string

---

mu4e/mu4e-headers.el

While I am reading a message in a split view, the cursor of mu4e-headers window moves to top after auto updation and rerun-search.
I found mu4e call mu4e-headers-goto-message-id but it failed to jump to the specific header if the buffer is currently inside unselect window.
Also mu4e~headers-highlight function has similar problem, but it works with with-current-buffer macro.

mu4e: Fix jumping to specific header in unselect window

---

man/mu-easy.1
mu/mu-config.c

Other than `MU_NOCOLOR`, there is a conventional environment variable `NO_COLOR`, which is shared across many other projects – see https://no-color.org.
This is a very simple change which would make `mu` support that.

mu-config: add NO_COLOR environment variable

---

mu4e/mu4e-view.el

This is necessary to display messages with UFT-8 chars when visiting the draft folder.  Here is an [example of such a message](https://github.com/djcb/mu/files/2824530/draft.txt).

mu4e: properly display messages in the draft folder (with gnus)

---

mu4e/mu4e-headers.el

Currently if you have new messages but are in another frame `*mu4e-headers*` isn't auto updated.

Look at all frames for header buffer when auto updating headers

---

mu4e/mu4e-actions.el

Here is a very simple patch that achieves what I want, though I am sure there are nicer ways of doing it.

Issue #1385: get mu4e-action-view-in-browser to show headers

---

mu4e/mu4e.texi

Noticed while rebuilding today's master.

Quote '@' symbols in texinfo's @code section

---

mu4e/mu4e-actions.el

Before this commit the HTML was looking as
```
From: From: email
To: To: email
```

Better conversion to HTML

---

mu4e/mu4e-actions.el

In addition to the [previous fix](https://github.com/djcb/mu/pull/1406), one also has to escape HTML entities.

Escape HTML entities

---

mu4e/mu4e-actions.el

Hi,
There was a traceback which looked like "void function error short" when the function `mu4e~action-header-to-html` was called.
Great software, keep going :slightly_smiling_face: !!
Thanks!

mu4e: fix a remaining local variable 'short'

---

lib/mu-msg.c

The current code is perfectly fine, and this commit doesn't change any logic
because the C++ order of operations rules do the exact same thing here with or without the additional parentheses.
However, GCC 9 with the `-Wparentheses` flag is emitting a warning when compiling mu due to the fact that in general mixing `&&` and `||` in the same line can be a source of confusion. This could be an issue if you wanted to compile `mu` using `-Werror`, for example:
```
mu-msg.c: In function 'accumulate_body':
mu-msg.c:461:23: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
461 |  if (bdata->want_html && is_html || !bdata->want_html && is_plain)
|      ~~~~~~~~~~~~~~~~~^~~~~~~~~~
```

Fix pedantic -Wparentheses warning generated by gcc 9

---

mu4e/mu4e-headers.el

- The documentation speaks of `SKIP-HOOK` which is not an argument;
- I do not understand why `get-buffer-window-list` is limited to the current frame (if we were viewing the message in another frame, should not we close it too?).

Fix mu4e~headers-remove-handler

---

configure.ac

Since mu seems to already gate Autoconf to have version >= 2.68, which was released back in 2010, it seems rather silly to not use more modern m4 macros, like for instance `LT_INIT` which requires libtool version >= 1.9b, which itself was released in 2004 and where the first stable version, libtool 2.2 was released back in 2008.
Any distro that has a sufficiently recent Autoconf has a recent enough libtool.

Replace AM_PROG_LIBTOOL with LT_INIT

---

mu4e/mu4e-context.el

Simple fix from #1455, to enable documented use of the `name` keyword argument in `make-mu4e-context-account`.

mu4e: fix `make-mu4e-context-account` to see `name` keyword arg

---

mu4e/mu4e-compose.el

Fixes unbalanced parens in mu4e-compose-context-policy, which prevents Custom mode UI working.
Using standard indentation helps prevent missing these little issues.

Balance parens in mu4e-compose-context-policy

---

README.org

this PR add a short description for users running openSUSE Linux distro. 
I could also initially not find `mu` in the pkg, so at least providing doc should be ok,

update with opensuse distro instructions

---

mu4e/mu4e-compose.el
mu4e/mu4e-headers.el
mu4e/mu4e-icalendar.el
mu4e/mu4e-main.el
mu4e/mu4e-utils.el
mu4e/mu4e-view.el
mu4e/org-mu4e.el
mu4e/org-old-mu4e.el

Previously both cl-lib.el and cl.el were used, now use only cl-lib.el.
Use lexical-binding where needed instead of requiring cl just for
`lexical-let`.
Replace some add-to-list with cl-pushnew as add-to-list is not
recommended in lisp program and anyway doesn't work properly with
lexical binding.

Completely use cl-lib and lexical-binding (rebase #1471)

---

lib/mu-store.cc

Updated today to latest sources and found the "personal" flag didn't work as expected.
In set_personal_addresses(), aside from updating the db, we also need to refresh the addresses in the Store itself, as this is subsequently used during indexing (this would fail to pickup addresses put in --my-addresses during index --reindex otherwise).
I also fixed the "FIXME" in each_contact_check_if_personal using personal_addresses() directly. I assume a GSList was only necessary due to the old code, so let's avoid copies.
In the for(auto) statements I noticed I got a lot of gcc warnings regarding comparisons with size_t, as 0 is deduced as int. I fixed one such occurrence, but I think it's better to use size_t explicitly in these cases.

Initialize my addresses

---

lib/tests/test-mu-common.c

On some systems (FreeBSD) en_US.utf8 doesn't exist.  Use a portable
locale en_US.UTF-8.

lib: Use more portable locale en_US.UTF-8

---

lib/tests/test-mu-maildir.c

Possible hostnames might have digits and - in them.  Crude regex to
allow hostnames that start with alnum followed by alnum or "-".
Fixes #1399

lib: Allow hostname of newbase to match alnum

---

mu/tests/test-mu-cmd.c

Fix test_mu_find_04 such that stderr has expected output.
With the mu command after options/expression nothing was printed.
We now have expected nonexistent muhome error.

tests: fix cmd test_mu_find_04 stderr output

---

mu4e/mu4e-compose.el

This has been driving me mad for a while: mu4e's M-< and M-> commands were not consistent with the standard ones.

Push mark on beginning/end of buffer

---

mu4e/mu4e-context.el

In document, mu4e-contexts is described which can be customed by user, why we don't define it with defcustom to let `custom-set-variables` work before loading mu4e.

mu4e: switch mu4e-contexts from defvar to defcustom

---

configure.ac

Changed autoconfig file to add support for emacs 28.xx versions building mu4e

mu configure.ac: allow emacs 28.xx to build mu4e

---

mu4e/mu4e-view.el

It allows the customization directly from Emacs Custom mode.  It is
done in a similar way as for `mu4e-view-attachment-actions'.

mu4e: define mu4e-view-actions with defcustom instead of defvar

---

mu4e/mu4e.texi

The `message-send` command already uses the variable `message-confirm-send` to check if a confirmation should be asked before sending.  Then, setting this variable is a more straightforward alternative for getting those confirmations before sending.

mu4e: inform alternative for getting confirmation before sending

---

mu4e/mu4e-view.el

when not necessary.
* mu4e/mu4e-view.el (mu4e~view-gnus): Require gnus-art here instead on
top of file.

Avoid loading all gnus package

---

mu4e/mu4e-utils.el

I occasionally find myself pressing escape to exit a menu choice in mu4e
and it's a bit unfortunate that nothing happens. As best I could tell,
since this is a C call, none of the keymaps are checked for
`(keyboard-quit)' so we need to explicitly check for ESC here.
----
#

mu4e-util: allow ESC to exit a choice selection

---

mu4e/mu4e-view.el

Commit edce6354160eccaf7559e038996421f7e5a885ec only loads it
dynamically when executing the function mu4e~view-gnus but as a
consequence many variables are undefined at compile time and, more
importantly, it is no longer possible to override the variable
gnus-display-mime-function with a let binding before calling
gnus-article-prepare-display

Load gnus-art when compiling

---

mu4e/mu4e-utils.el

Instead of hard coding the buffer name `" *mu4e-update*"`, use the buffer name defined in `mu4e~update-name`.  Also, the default name defined in `mu4e~update-name` were changed to match the previously hard-coded invisible buffer name.

mu4e: use `mu4e~update-name` de facto

---

mu4e/mu4e-compose.el

If no region is selected, mu4e-fill-paragraph will delete trailing whitespace on
all lines in the buffer.  This might not be desired, e.g. when adding a
signature to the mail which is delimited by the line '-- '.

mu4e: restrict deleting trailing whitespace to region

---

lib/mu-container.c
mu/test-mu-threads.c

Hi Guys,
First of all, thanks a lot for all the work you did around mu, it works very well.
I used it daily and it saves me a lot of time.
At my company I "converted" couple colleagues to use mu (mu4e).
We are mainly working on the kernel and most of my colleagues reported me that the thread view can be very confusing if there is replies on couple emails (patchs), typically replies on patchset list.
So I started to look at the internal mu source code to see if I can change the thread output.
I've been able to have something that sort as we wanted to.
I don't want to impose my way of sorting, this patch is really PoC to also have your opinion on the subject.
I send you this pull-request because some other people might be interested other than just my colleagues.
I tried to explain as much …

mu: add an option to ignore leader when sorting childs of a thread

---

.dir-locals.el
.editorconfig
.gitignore
.mailmap
man/mu-server.1
mu4e/mu4e-actions.el
mu4e/mu4e-compose.el
mu4e/mu4e-context.el
mu4e/mu4e-contrib.el
mu4e/mu4e-draft.el
mu4e/mu4e-headers.el
mu4e/mu4e-icalendar.el
mu4e/mu4e-main.el
mu4e/mu4e-mark.el
mu4e/mu4e-message.el
mu4e/mu4e-org.el
mu4e/mu4e-proc.el
mu4e/mu4e-speedbar.el
mu4e/mu4e-utils.el
mu4e/mu4e-vars.el
mu4e/mu4e-view.el
mu4e/mu4e.el
mu4e/mu4e.texi
mu4e/org-mu4e.el

As mentioned in #1571 completely messes up indentation of Emacs lisp files.
The commit 173deff6a03bae1171e39ca8da916386ca9bbf67 ("editorconfig: Don't misconfigure indentation for Emacs lisp files") has more details.
In addition to removing the `.editorconfig` configuration this pr configures `.dir-locals.el` and then fixes the indentation.
And then it also fixes quite a few other assorted issues I ran into along the way.  Let me know if this does too much.  I can split this up into more pull-requests and explain in more details why I did what I did.

Keep editorconfig from misconfiguring indentation for Emacs lisp files

---

mu4e/mu4e-context.el
mu4e/mu4e-headers.el
mu4e/mu4e-main.el
mu4e/mu4e-utils.el

This is in continuation of #1562.
This PR allows using revert-buffer in mu4e-main instead of binding "g" to mu4e.
`mu4e~start` is no more using `mu4e-index-updated-hook`, the call is directly done in `mu4e-info-handler` which is cleaner.
Main buffer is correctly updated when quitting headers.
Mode-line is updated when changing context.

Fix revert buffer

---

mu4e/mu4e-view.el

In the keybinding defintions for mu4e-view-mode-map, the variable
mu4e-view-use-gnus was used quoted in an if condition, which means that the
condition always evaluated to true. Therefore, M-q would always be bound to
article-fill-long lines and never to mu4e-view-fill-long-lines.

mu4e: Fix quoting in M-q keybinding definition

---

mu4e/mu4e-view.el

With the current version of the mu server, it is not possible open
attachments, because the server expects symbols as parameters, but
mu4e sends strings.
This change fixes this.

Fix of the attachment actions

---

mu4e/mu4e-vars.el

Due to a breaking change we have to request this explicitly in
Emacs 27.  Earlier Emacs versions do the right thing by default.
If the effect of a face does not extend to the edge of the window,
then attributes such as the background color or underline cease to
be used for more that the width of a single character, which is not
appropriate for a face intended to highlight a complete line.
See https://debbugs.gnu.org/cgi/bugreport.cgi?bug=37774.

mu4e: extend mu4e-header-highlight-face to edge of window

---

mu4e/mu4e-compose.el
mu4e/mu4e-utils.el

This fixes what I believe to be two bugs:
- The first is in `mu4e-info-handler` where `save-window-excursion` is now called instead of just selecting the `mainbuf` window. Previously, the main-mu4e window was selected (if visible) after `mu4e-update-index` is called (directly or through the update timer). The result was that the pointer would jump away from a currently selected window. 
- The second is in `mu4e-compose.el`. Previously, `(widen)` was called right after `(mu4e~compose-hide-headers)`. There were two problems: First the headers that were just hidden are immediately shown. Second if some headers were previously hidden before that hook is executed, some header fields were corrupted.

Misc fixes

---

HACKING
guile/mu-guile.c
guile/mu-guile.texi
lib/mu-runtime.h
man/mu-index.1
man/mu.1
mu4e/mu4e.texi

Change man pages so that they honor the new mu config directory.
Question: `mu-script.1` Where are the scripts stored? I guess not in the `.cache` directory. I left `.mu/scripts`.

~/.mu -> ~/.cache/mu

---

mu4e/mu4e-main.el

Ran into this small bug when trying to hide the display of personal messages in the main view. "insert" expects a string, this fix returns an empty string when `mu4e-main-buffer-hide-personal-addresses' is set.

fix `mu4e-main-buffer-hide-personal-addresses'

---

lib/mu-store.cc

On Debian 9 random memory was printed with the original buffer size
and valgrind complained about the use of uninitialized memory.

mu-store: enlarge buffer for strftime

---

mu4e/:show-unread t

I think the docstring is correct and the variable setting is wrong -- the code elsewhere  (mu4e~start) seems to check hide-unread property.
Once the discrepancy between doc string and code is fixed, the info file will need updating, as this variable is shown verbatim in 7.2 Bookmarks node.

Is it :hide-unread or :show-unread

---

mu4e/mu4e-view.el

In the current `master` branch, setting up an `m4ue-view` buffer runs the `mu4e-view-mode-hooks` entries on a buffer that is only partway through initialization: the buffer is missing the `mu4e~view-message` buffer-local variable with the actual message.  The code sets that variable after entering `mu4e-view-mode`.  This ordering means the current message is unavailable to the hooks, and the hooks can't adjust their behavior based on the message properties.
To fix that bug, it is not enough to just set `mu4e~view-message` before entering `mu4e-view-mode`.  Major mode changes clobber buffer-local variables, as part of standard Emacs behavior ([ref](https://www.gnu.org/software/emacs/manual/html_node/elisp/Creating-Buffer_002dLocal.html#Creating-Buffer_002dLocal)).  Marking the …

Make mu4e~view-message available to mu4e-view-mode-hooks.

---

mu4e/mu4e-main.el

Change the spaces to tab to be consistent with the other entries in the
main view.

mu4e: change spacing in main view for info section

---

mu4e/mu4e-headers.el

Fix mu4e-headers-mark-or-move-to-trash() to pick right trash folder when
:no-trash-flag option is used in a context.

Fix mu4e-headers-mark-or-move-to-trash()

---

mu4e/mu4e-context.el

The current `make-mu4e-context-account` will change bookmark items to
```
("NOT maildir:\"/trash\" and :name" "Unread messages" :query "flag:unread AND NOT flag:trashed" :key 117)
```
instead of modifying the query properly.
This sets the correct query for bookmarks when no-trash-flag is used.

Fix `make-mu4e-context-account()` set incorrect query for bookmarks

---

mu4e/mu4e-contrib.el
mu4e/mu4e-utils.el

Some completion engines (like "flx") decorate the strings that they
return.  If MU4E passes such a string down to MU, the "format" call
preserves the text properties in the generated S-expression, producing
an invalid query.  MU4E itself has no interest in those decorations,
so strip them out as early as possible from all prompts that use
mu4e-completing-read-function.

Strip properties from mu4e-completing-read-function results.

---

mu4e/mu4e-view.el

Resolution for a tiny annoyance:  adds a space between the verification status of the signature and the signers

Missing space between sig verification and signers

---

lib/mu-maildir.c
lib/mu-msg-part.c
man/mu-index.1

Isync uses this by default on Windows where ':' is an invalid character
in file names. Also try to preserve the existing separator character
when generating a new file name.

Allow ';' as a Maildir flags seperator

---

.github/workflows/build-and-test.yml

currently this runs tests on the latest Ubuntu LTS and the latest macOS
should be straightforward to run tests on any of the other [supported
environments](https://github.com/actions/virtual-environments) or in a Docker
container
as discussed in #1723

add CI: run test suite with GitHub actions

---

mu4e/mu4e-icalendar.el

- The multipart/alternative was problematic with Outlook (see https://github.com/djcb/mu/issues/1729).  
- Since a text reply is possible with the ical attachment, the original email quotation is saved to the kill-ring.

Fix accepting ical RSVP with Outlook

---

mu4e/mu4e.el

Some Emacs user may never use desktop.el, We don't need to require desktop.el
for them.

mu4e: Delay the execution of workaround for desktop.el

---

mu4e/mu4e.texi

The documentation references the obsolete function `org-mu4e-store-and-capture`. Updated it to `mu4e-org-store-and-capture`.

Fix typo in org-mode links section documentation

---

mu4e/mu4e-utils.el

Ideally we should separate the log buffer creation code so this van be
done a bit more cleanly. For now however only set so-long-mode once
otherwise you end up spamming the messages with constant:
Changed to so-long-mode (from fundamental-mode) on account of line length.  C-c C-c to revert. [36 times]
As the messages keep rolling in.

mu4e/mu4e-utils: only set so-long-mode once

---

lib/utils/mu-str.h

When this function is declared const or pure, clang at -O1 or higher optimizes
away the call to mu_str_size_s() inside mu_str_size(), so that it ignores its
argument and returns whatever is in mu_str_size_s()'s static buffer.
Found when test-mu-str failed while testing an update of mu in OpenBSD's ports tree.

Don't declare mu_str_size_s() with the const attribute.

---

NEWS.org
mu4e/mu4e-vars.el

mu4e-contact-rewrite-function was obsoleted in 1.4, but the entry in
NEWS.org entry, and the make-obsolete-variable call, referred to it as
mu4e-contacts-rewrite-function. (Should be "contact", not "contacts".)

NEWS.org, mu4e-vars.e.: fix spelling mu4e-contact-rewrite-function

---

lib/index/mu-indexer.cc
mu4e/mu4e-utils.el

Once your log buffer has filled up every new entry causes you to jump
back to the top of the log. Stop this happening by wrapping the
clean-up in save-excursion.

mu4e/mu4e-utils: save our position before deleting old data

---

mu4e/mu4e-utils.el

- introduce private function mu4e~image-width-scale:
determine the width to use for proportional scaling based on the image width, height and the max
restrictions.
- use it in mu4e-display-image

Satisfy both max height and width for images in view

---

lib/index/mu-scanner.cc
lib/utils/mu-logger.cc

The latest code cannot be successfully compiled on windows:
```sh
mu-logger.cc:81:40: error: 鈥▒::strerror鈥▒ has not been declared; did you mean 鈥▒g_strerror鈥▒?
81 |                           << ": " << ::strerror(errno) << std::endl;
mu-scanner.cc:167:70: error: 鈥▒strerror鈥▒ was not declared in this scope; did you mean 鈥▒g_strerror鈥▒?
167 |                 g_warning("'%s' is not stat'able: %s", path.c_str(), strerror (errno));
```
The cause of this error is that the header file required by `strerror` does not explicitly contain: `cstring.h`.
This PR fixed it.

[MSYS2] Added missing include files

---

mu4e/mu4e-headers.el

Being able to pipe through shell from the headers view is
convenient for some use cases, so wire it up to work.
Resolves #1752
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>

mu4e-headers: allow pipe through shell from headers view

---

configure.ac
lib/utils/mu-logger.cc

timegm() is no longer used in the mu source base. I am trying to find what are the minimal changes to allow configuring this code in mingw/msys (which is my preferred basis for compiling Emacs itself).

Remove configuration check for timegm()

---

lib/mu-maildir.c

mu_maildir_get_new_path() is on charge of renaming messages, moving them to different folders. When new_name is 0, it reuses the old name and properly identifies the flags separator. However, when new_name is 1 (which is needed, for instance, for mbsync), it always creates a file name with ':' as flags separator, which is incorrect on MS-DOS based filesystems.

mu_maildir_get_new_path() did not use the right flags separator

---

mu4e/mu4e-headers.el

Got a few errors in `*mu4e-headers*` while skimming through a junk folder due to a nil :from address.
I'd rather have mu4e-user-mail-address-p not called in such cases, so we filter it earlier.
There's a similar second instance in mu4e-view.el:272 , when constructing "from-to", but I'm not sure if that's applicable? (I couldn't select a message that would trigger it).

Check for nil before calling mu4e-user-mail-address-p

---

mu4e/mu4e.texi

As far as I understand, this is a legitimate usage of `mu4e`, isn't it?

Add reference about read-mail-command to mu4e.texi.

---

mu4e/mu4e-compose.el
mu4e/mu4e-contrib.el
mu4e/mu4e-headers.el
mu4e/mu4e-icalendar.el
mu4e/mu4e-speedbar.el
mu4e/mu4e-view.el
mu4e/org-mu4e.el

This is cleaner and help when debugging to use functions in hooks instead of lambdas.

Use functions instead of lambdas in add-hook calls

---

mu4e/mu4e-view.el

When this option is set to 'known and the needed key is not yet in the user's
keyring, mu4e may hangs forever unable to verify email so lets user set this
variable globally to 'never to prevent this issue.

Disable `mm-verify-option` let-bounded in `mu4e~view-gnus`

---

mu4e/mu4e-view.el

In mu4e~view-gnus, mu4e-view-mode derive from gnus-article-mode which derive
from gnus-mode which derive from special-mode:
(get 'mu4e-view-mode 'mode-class) => special.

No need to call `read-only-mode` when buffer is already read-only

---

mu4e/mu4e-compose.el

Actual code loop through buffer-list even when `message-kill-buffer-on-exit` is nil.

Avoid looping through buffer-list when not needed

---

mu4e/mu4e-icalendar.el

When clicking "Accept" event, if the entry is new
it is not added to the Org file, besides having
gnus-icalendar-org-enabled-p set to true.
This modification changes that, so that a new entry
is added or an existing one is modified.

Add Org entry when accepting event

---

mu4e/mu4e-proc.el

Avoid using 'head', 'sed' or other POSIX commands to extract the version number when Emacs can do it. This allows installing just 'mu', without the extra unix tools in a Windows environment, or run 'mu' from MSYS but do not expose the rest of the MSYS environment (needed if one wants to rely on Windows cmd.exe shell for other tasks, for instance).

Do not use shell commands to extract version number

---

mu4e/mu4e-main.el
mu4e/mu4e-utils.el

Until now, the bookmark queries were sent to mu in their original form.  Thus,
if you have `mu4e-query-rewrite-function` set, the numbers shown next to the
bookmarks didn't reflect the actual number of query results you'd get when
opening a bookmark view.
With this commit, the `mu4e-query-rewrite-function` is applied and the result
is sent to mu for evaluation (in `mu4e~start`) and the likewise the rewritten
queries are used to find the matching one in the last query results (in
`mu4e~main-bookmarks`).
* mu4e/mu4e-utils.el (mu4e~start): Send the rewritten queries for evaluation to
mu.
* mu4e/mu4e-main.el (mu4e~main-bookmarks): Compare last mu query results with
rewritten queries.
I think this change makes sense for anyone using a
`mu4e-query-rewrite-function`.
My personal use-case is that …

Use mu4e-query-rewrite-function also for computing bookmark counts

---

configure.ac

Add a --disable-readline argument to the 'configure' script, removing the need of libreadline which pulls ncurses and a lot of other files, not needed when mu is only used from inside emacs.

Make libreadline really optional.

---

mu4e/mu4e-view.el

I found a null byte at eol added probably by error in commit 57d38aa7070ad9cb108bfffb1cf17f99f79c1322.
See https://debbugs.gnu.org/cgi/bugreport.cgi?bug=44486 for infos about null bytes in lisp buffers.
Also here the output of shell command `rg mu4e-view-save-attachment-multi` from mu4e directory (file is recognized as binary):
```sh
mu4e-view.el
140:     ("Ssave multi" . mu4e-view-save-attachment-multi)
WARNING: stopped searching binary file mu4e-view.el after match (found "\u{0}" byte around offset 22103)
```

Remove null byte added probably by error

---

mu4e/mu4e-utils.el

Oftentimes I get this error when quitting mu4e by tying `q` in the mu4e buffer.
```
Debugger entered--Lisp error: (error "Selecting deleted buffer")
#f(compiled-function (buf) #<bytecode -0xd27d395f5e1de6d>)(#<killed buffer>)
mapc(#f(compiled-function (buf) #<bytecode -0xd27d395f5e1de6d>) (#<killed buffer> #<buffer  *Minibuf-1*> #<killed buffer> #<buffer  *mu4e-loading*> #<buffer *Help*> #<buffer magit: auctex> #<buffer *scratch*> #<killed buffer> #<buffer preview.el.in> #<buffer preview.el> #<buffer *~/tmp/3 output*> #<buffer  *Minibuf-0*> #<buffer *Messages*> #<buffer  *Echo Area 0*> #<buffer  *Echo Area 1*> #<buffer  *code-conversion-work*> #<buffer  *eldoc*> #<buffer *~/tmp/1 output*> #<buffer *TeX Help*> #<buffer 3.log> #<buffer  *mu4e-proc*> #<buffer  *appease-gnus*> #<buffer  *gnus …
```

Debugger entered--Lisp error: (error "Selecting deleted buffer") when quitting mu4e

---

mu4e/mu4e-headers.el
mu4e/mu4e.texi

This pull requests adds TAB-completion for search query keywords (like `from:`, `subject:`, etc.), and also for their values in case they are fixed (like with `flag:`) or can be determined at runtime (like for `maildir:`, and `mime:`).
I didn't know which Emacs version mu4e requires so I've `fboundp`-checked the needed `minibuffer-with-setup-hook` macro (available since Emacs 25.1) and fall back to "no completion" if that's undefined.

Completion for search query keywords and fixed or determinable values

---

lib/mu-contacts.cc

The behaviour suggested in #1857 (and the old behaviour of mu4e when that did the sorting) is that if exactly one of ci1 or ci2 was seen in the last 15 days, then that should be selected as first in the order by ContactInfoLessThan. As it stands, we return the most recent of ci1 and ci2 as least in the order only when ci1 was seen in the last 15 days. So if ci2 was seen in the last 15 days, but ci1 was not, it will fall through to a comparison on frequency; while if ci1 was seen in the last 15 days, but ci2 was not, it will always return ci1 as least. This is not antisymmetric in ci1 and ci2.

Make order relation on contacts antisymmetric

---

mu4e/mu4e-headers.el
mu4e/mu4e.texi

I have many maildirs (because I also use other clients, like a mobile one, which haven't the searching super-powers of mu) and configured shortcuts for them.  Frequently, I want to read such a maildir but do not want to see all messages but just unread messages or messages with attachments.  For such purposes, I've added an optional prefix arg to `mu4e-jump-to-maildir` which allows the `maildir:"/foo/bar"` query to be refined/extended before execution.  So it's basically the same as for bookmarks, i.e., `B` instead of `b`.
If you want, I can also add a new command bound to `J` which calls `mu4e-jump-to-maildir` with non-nil prefix arg so that `j` and `J` are really analogous to `b` and `B`.
I've adapted docstring and texi docs accordingly.
I also refactored the now two usages of the "read …

mu4e-jump-to-maildir: offer editing the query when a prefix arg is given

---

mu4e/mu4e-headers.el

This wraps up some change that somehow didn't get applied when merging PR #1921
and also offers completion when editing a bookmark (which I've forgotten in
that PR).

Read query with completion also when editing a bookmark

---

mu4e/mu4e.texi

It's not documented in gnus-icalendar, so the explanation comes straight from my reading of the code.
Being able to customize the capture template partially addresses the issue I raised in #1912. gnus-icalendar supports this, in an undocumented way, and the code comments suggest the details may change eventually.

Documented icalendar capture template

---

mu4e/mu4e-view.el

where `handle' may not be a list (here a marker when I had error).
So ensure it is a list.

Fix error in mu4e-view-gnus-save-mime-parts

---

mu4e/mu4e-view-common.el
mu4e/mu4e-view-gnus.el

Without this, the clicking on the URL just show `insert-for-yank: Buffer is read-only: #<buffer *Article*>` but no action is taken.  <kbd>C-h k</kbd> and then clicking reports:
```
There were several key-sequences:
<down-mouse-1> at that spot runs the command mouse-drag-region
<mouse-2> (translated from <mouse-1>) at that spot runs the command mouse-yank-primary
Those are influenced by `mouse-1-click-follows-link'
They're all described below.
<down-mouse-1> at that spot runs the command mouse-drag-region (found
in global-map),
...
<mouse-2> (translated from <mouse-1>) at that spot runs the command
mouse-yank-primary (found in global-map),
...
```
After, I get
```
There were several key-sequences:
<down-mouse-1> at that spot runs the command mu4e~view-browse-url-from-binding
<mouse-2> …
```

Make URLs clickable again

---

mu4e/mu4e-view-gnus.el

The `From` link triggers _reply_ and the email links launch _mu4e_ (**not** `message-mail`).

mu4e/view-gnus: Make Gnus email clickable links work

---

mu4e/mu4e-view-gnus.el

[ivy](https://github.com/abo-abo/swiper) is an alternative completion framework to *helm*. I added an extra conditional to use `completing-read` to save attachments (`mu4e-view-save-attachments` in `mu4e-view-gnus.el`) when *ivy* is in use.

Add ivy completion when saving attachments

---

mu4e/mu4e-headers.el

When marking threads as read things are slowed down by echoing the
thread path to the mini-buffer. I assume this is left over debug but
if needed for something else should probably be a log call.

mu4e/mu4e-headers: remove excess message output

---

mu4e/mu4e-compose.el
mu4e/mu4e-draft.el

Emacs has several standard keybindings
C-x m   compose-mail
C-x 4 m compose-mail-other-window
C-x 5 m compose-mail-other-frame
This patch fixes the creation of new mail buffers to respect the
latter two keybindings, C-x 4 m and C-x 5 m.
Note that there is already the variable mu4e-compose-in-new-frame
which if true opens in a new frame.  That will still work for C-x m
and C-x 5 m, but if the user runs C-x 4 m, it switches to other-window
as it assumes the keybinding takes precedence.  This behaviour can be
changed within mu4e~draft-open-file.
See also #1928

Respect switch-function in compose-mail.

---

mu4e/mu4e-compose.el

This fixes the fact that `:disposition` was advertised but not queried.  In addition, one has the possibility to add a `:description` and to attach buffers.  This may be used in the resolution of https://github.com/djcb/mu/issues/1956.

mu4e/compose: attach buffers & files setting any property

---

mu4e/mu4e-icalendar.el
mu4e/mu4e-view-gnus.el

This composes the response before any hook is run which is important so that, if those hooks modify the message, they are aware that some MML is present.  In particular, this is needed to have the compatibility with the org-msg package; see https://github.com/djcb/mu/issues/1956

mu4e/ical: Compose the response attaching the calendar

---

mu4e/mu4e-mark.el

When running `u4e-mark-execute-all` with any prefix-arg you can skip the confirmation-prompt. The potential for accidentally hitting this is quite low.

skip confirmation when executing marks

---

mu4e/mu4e-view-gnus.el

Was not removed with commit 55d8d20771405465f4d75649eab7b8a462cc4e31.

Remove unneeded `or` clause in mu4e-view-save-attachments

---

lib/mu-store.cc
lib/utils/mu-error.hh
lib/utils/mu-sexp.cc
lib/utils/mu-utils.cc
lib/utils/mu-utils.hh
lib/utils/test-utils.cc

All the call site that issues a `va_list` in the second argument are converted to use `vformat`.
There is also a unrelated type cast to suppress a compiler warning.

seperate Mu::format and Mu::vformat

---

mu4e/mu4e-view-gnus.el

Using cl-loop is much simpler and readable, than using mapconcat+seq+seq.
Also it avoids requiring seq (which is not done actually).

Fix #2006 by using cl-loop in mu4e-action-view-in-browser instead of seq

---

mu4e/mu4e-view-gnus.el
mu4e/mu4e-view-old.el

Users usually have `<home>` and `<end>` bound in their configuration,
for Spacemacs the default is “move-beginning-of-line” and “move-end-of-line”.
The mu4e view mode should not rebind basic navigation keys like these.

mu4e-view: remove <home> and <end> bindings

---

mu4e/mu4e-actions.el
mu4e/mu4e-compose.el
mu4e/mu4e-context.el
mu4e/mu4e-contrib.el
mu4e/mu4e-draft.el
mu4e/mu4e-headers.el
mu4e/mu4e-icalendar.el
mu4e/mu4e-lists.el
mu4e/mu4e-main.el
mu4e/mu4e-mark.el
mu4e/mu4e-message.el
mu4e/mu4e-org.el
mu4e/mu4e-proc.el
mu4e/mu4e-utils.el
mu4e/mu4e-vars.el
mu4e/mu4e-view-common.el
mu4e/mu4e-view-gnus.el
mu4e/mu4e-view-old.el
mu4e/mu4e-view.el
mu4e/mu4e.el
mu4e/obsolete/org-mu4e.el

At the start of mu4e/* files, the license has been wrongly attributed
to GNU Emacs instead of mu4e.
Fixes https://github.com/djcb/mu/issues/2019

mu4e/*: fix license notice at the start of source files

---

mu4e/mu4e-view-gnus.el

Previously helm-comp-read-use-marked was bound also when completing on
a directory for saving attachments (when using a prefix argument). This
returned a list with the selected directory, which caused an error.

Fix bug with helm completing-read when saving attachments

---

mu4e/mu4e-mark.el

This prevent deleting overlays added by third party packages working as well
with overlays in mu4e-headers e.g. thread-folding , and probably in mu4e
itself as well with future features.  Also having a named overlay allows in
future features to modify any other overlays but these ones.
As it is this patch doesn't modify the actual behavior.

Only remove mark overlays in `mu4e-mark-at-point`

---

mu4e/mu4e-headers.el

This fixes the issue introduced by 50f6f539 where header navigation
would break when `visual-line-mode` was enabled. Previously,
`forward-line` was used in `mu4e-view-headers-next`, which disregarded
visual lines and moved by logical lines, but this was changed to
`line-move`, which moves by visual lines when `line-move-visual` is
non-nil (the default when `visual-line-mode` is enabled). Thus, when
the current header line was wrapped and a message was open in the
split view, `mu4e-view-headers-next` would move to the next visual
line in the headers buffer (the same message), and then jump back to
the start of the previous line, preventing switching to the next
message.
This would also throw off navigation when `mu4e-view-headers-next` was
used with a prefix argument, since it would move …

Fix #2044: broken header movement with visual-line-mode

---

lib/mu-query.cc
lib/mu-server.cc

mu-query.cc:
- make_related_enquire: don't include first query in qvec, we already have all
thread IDs we need to query in thread_ids.
- run_related: always sort first query by date, as explained in the code
comment.
- run_related: include qflags (in particular ascending vs descending) in
leader_qflags.
- run_threaded: don't limit results to maxnum, that results in threads
potentially being cut off.
mu-server.cc:
- output_sexp: don't limit results to maxnum so as to match the behaviour of
mu find (and avoid cutting off threads).
Fixes #1924 and #1911.

query: fix include-related.

---

mu4e/mu4e-headers.el

Skip invisible text at BOL possibly hidden by
the end of another invisible overlay covering
previous EOL.
This patch affects people using mu4e-thread-folding-mode but change nothing
when using mu4e as it is.

Fix mu4e-headers-prev with invisible lines

---

mu4e/mu4e-message.el

**Describe the bug**
When using `mu4e-view-use-old`, then messages are shown without linebreak.
**To Reproduce**
Use the "old" view and open an email with multiple lines or reply to an email (also affects cited email).
This is caused by `mu4e-message-outlook-cleanup`. Where linefeed instead of carriage return is replaced. Looks like this was introduced in commit `539a946a` and was correct before. 
**Environment**
happens on both linux and Mac OS X
**Checklist**

[mu4e bug] (1.6.0) - messages in old view are shown without line break

---

mu4e/mu4e-headers.el

Found this by accident when debugging something and reading the code. However, the resulting sentence does not make complete sense to me, perhaps it's time to reword it a bit. Maybe I'm missing something, though. Feel free to edit my patch if so :)

Fix typo in docstring

---

mu4e/mu4e-org.el
mu4e/mu4e.texi

- There's a default function that extracts the subject but users can define their own function. 
- Added a mention in the documentation.
- Based on code from v1.4.15.

Customize the mu4e org link description

---

mu4e/mu4e-view-gnus.el

This MR adds a simple function, which loops over the different parts of a message and makes use of gnus internal function to toggle the HTML part of it.
Fixes: https://github.com/djcb/mu/issues/2013

mu4e: Add back the `h' keybinding to toggle HTML view in a gnus article

---

mu4e/mu4e-view-gnus.el

Different MIME configurations need a fallback logic. 
Instead of looking for the attachment "fname" in the structure
```elisp
("attachment" . (filename "fname"))
```
we find the same file name in the structure
```elisp
("mime-type" . (name . "fname"))
```
by searching, since we don't know the MIME type beforehand.
Should solve #2116 .

Attachments Saving Improvment

---

man/mu-init.1

Hi,
The manpage markup in `mu-init` is broken and renders like this when escape sequences are enabled:
```
<my-email-address> can be either a plain e-mail address (such as
foo@example.com), or a regular-expression (of the 'Basic POSIX'
flavor), wrapped in 0
```
This PR fixes the markup to what I *think* was meant. Also, I think the second '/' was missing in the wrapped regex email address notation.
With this fix, it reads like:
```
<my-email-address> can be either a plain e-mail address (such as
foo@example.com), or a regular-expression (of the 'Basic POSIX'
flavor), wrapped in / (such as /foo-.*@example\.com/).
```
The '/' as well as '/foo-.*@example\.com/' are bold.

Fix mu-init manpage markup

---

mu4e/mu4e-message.el
mu4e/obsolete/org-mu4e.el

This fixes some `declare-function` statements referencing the now-gone `mu4e-utils.el`.
BTW, I've already sent you this patch by mail on August, 31st, but never got a response.  Did your spam filter classify my mails as spam, or is `git send-email` simply a way to contribute that you are not interested in, or is that fine but should go to the mailinglist rather than your private mail address to allow for broader discussion?

Fix declare-function statements referencing the now-gone mu4e-utils

---

mu4e/mu4e-helpers.el

It actually returns a buffer-name whereas it should return a buffer
object which make `mu4e~switch-back-to-mu4e-buffer` fail because
`buffer-live-p` expects a buffer object.

Fix `mu4e-get-view-buffer` (#2132)

---

mu4e/mu4e-headers.el
mu4e/mu4e-helpers.el

This allows to have a function returning a window as value of
`mu4e-split-view`.  I'm using this patch since quite some time locally with the
following function.
```el
(defun th/mu4e-split-view ()
(let* ((headers (mu4e-get-headers-buffer))
(headers-win (and headers (get-buffer-window headers)))
(view (mu4e-get-view-buffer))
(view-win (and view (get-buffer-window view))))
(cond
;; There's a view window, just use it.
(view-win view-win)
;; Just one window, split sensibly, i.e., horizontally or
;; vertically depending on geometry.
((one-window-p) (split-window-sensibly))
;; Otherwise, use the tallest window.
(t (car (sort (delq headers-win (window-list))
(lambda (a b)
(> (window-height a) (window-height b)))))))))
(setq mu4e-split-view #'th/mu4e-split-view)
```

Allow a function as mu4e-split-view value

---

mu4e/mu4e-headers.el

On master, `mu4e~update-buffer` has been renamed to `mu4e--update-buffer` but some references haven't been adapted.  When `mu4e-display-update-status-in-modeline` is non-nil, one gets the following error on every search:
``` emacs-lisp
Error during redisplay: (eval (concat (propertize (mu4e-quote-for-modeline "T maildir:\"/Fastmail/INBOX\"") 'face 'mu4e-modeline-face) " " (if (and mu4e-display-update-status-in-modeline (buffer-live-p mu4e~update-buffer) (process-live-p (get-buffer-process mu4e~update-buffer))) (propertize " (updating)" 'face 'mu4e-modeline-face) ""))) signaled (void-variable mu4e~update-buffer)
```
This PR fixes those two leftovers.

Fix refs to mu4e~update-buffer which has been renamed to mu4e--update-buffer

---

mu4e/mu4e-view.el

This is needed when gnus is used along mu4e for other purpose like
reading News, in this case gnus rename `gnus-article-buffer` and we
end up with an unrelated buffer-name in mu4e.

Reset `gnus-article-buffer` in mu4e-view (#2139)

---

configure.ac

Current version checks for enabling mu4e don't include checking for Emacs 29, as such installing mu when using Emacs 29 does not appear to install mu4e. This suggestion changes that behavior.

Add Emacs v29 support for enabling mu4e

---

mu4e/meson.build

In the new build system we call batch-byte-compile manually for incremental compilation. Sadly the default behavior of emacs is to load the byte-compiled version of a source file, even if it refers to an older version. After a git update, this results in emacs loading the existing (old) source when other sources are compiled, which is incorrect.
A warning is emitted though:
```Source file ‘~/src/mu/build/mu4e/mu4e-view.el’ newer than byte-compiled file; using older file```
A simple fix is to use load-prefer-newer in the rule to always avoid loading stale byte-compiled files.

Ignore existing compiled files when byte-compiling

---

mu4e/mu4e-headers.el

To mark only the first message in the thread as orphan, allowing to
replicate the thread structure used by mutt and other clients.
This way it might be possible to replicate the same threading style from mutt. For example, with this configuration:
```elisp
(setq mu4e-headers-thread-mark-as-orphan 'first
mu4e-headers-thread-child-prefix '("├>" . "├▸ ")
mu4e-headers-thread-first-child-prefix '("├>" . "├▸ ")
mu4e-headers-thread-last-child-prefix '("└>" . "└▸ ")
mu4e-headers-thread-connection-prefix '("│" . "│ ")
mu4e-headers-thread-single-orphan-prefix '("─>" . "─▸")
mu4e-headers-thread-orphan-prefix '("┬>" . "┬▸"))
```
I can have something like that:
```
12/17/21   Sa   John    ┬>Some orphan thread..
14:08:36   Nau  John    ├>
15:13:33   Nau  John    └>
12:27:12   S    Anne    A regular …
```

mu4e-headers: Add mu4e-headers-thread-mark-as-orphan option

---

mu4e/meson.build

`mu4e` expects this file when activating the [A]bout link in `mu4e-main`
view, but when building the `mu-git` package from the AUR, this file
did not appear in the resulting package.
Now this file is not lost.

meson: Install mu4e/mu4e-about.org

---

mu4e/mu4e-main.el

Based on the `:tstamp` key in `mu4e-index-update-status` plist. 
Looks like this:

Last updated timestamp in main screen

---

mu4e/mu4e-search.el

As the title suggests, this commit adds completion support for the known List-Id values after the search keyword `list:` just like we already support email address completion after `to:`, `from:`, and friends.

Add support for List-Id completion (list:<List-Id>)

---

mu4e/mu4e-headers.el

for mu4e-header buffers, this displays the search query in
`M-x list-buffers` instead of showing an empty path column.

Assign `list-buffers-directory`

---

mu4e/mu4e.texi

This typo prevented the build:
```
[...]
[98/121] Generating mu4e/mu4e_info with a custom command
FAILED: mu4e/mu4e.info
/usr/bin/makeinfo -o /Users/fintel/Repos/notmine/mu/build/mu4e/mu4e.info /Users/fintel/Repos/notmine/mu/mu4e/mu4e.texi -I /Users/fintel/Repos/notmine/mu/build/mu4e/..
/Users/fintel/Repos/notmine/mu/mu4e/mu4e.texi:55: warning: undefined flag: VERSION.
/Users/fintel/Repos/notmine/mu/mu4e/mu4e.texi:3748: @t expected braces.
/Users/fintel/Repos/notmine/mu/mu4e/mu4e.texi:3748: Misplaced {.
/Users/fintel/Repos/notmine/mu/mu4e/mu4e.texi:3748: Misplaced }.
/Users/fintel/Repos/notmine/mu/mu4e/mu4e.texi:3748: @t missing close brace.
makeinfo: Removing output file `/Users/fintel/Repos/notmine/mu/build/mu4e/mu4e.info' due to errors; use --force to preserve.
[...]
ninja: build …
```

Fixed typo in mu4e.texi

---

mu4e/mu4e-contacts.el
mu4e/mu4e-search.el

I guess the change in `mu4e-search.el` is pretty self-explanatory.
Wrt. `mu4e-contacts-info`: `contacts` is a list with entries of the form `(rank
. full-mail-address)` where `full-mail-address` is a string like `"Name"
<mail@address.com>` and not a contact plist.

Add support for flag:personal & fix mu4e-contacts-info

---

mu4e/mu4e-view.el

`mu4e-view-mode-map` was initialized from a sparse keymap and eventually passed to `suppress-keymap` in order to remove bindings to `self-insert-command` which obviously make no sense in read-only buffers.  However, `suppress-keymap` also remaps all digits and the minus sign to make prefix args, i.e., pressing 8 would be equal to `C-u 8` and `-` got bound to `negative-argument` instead of `mu4e-view-mark-for-unflag` as defined.
While `suppress-keymap` has a `NODIGITS` arg to suppress the rebinding of digits and minus sign (which would also mean that pressing a digit would try inserting that digit and lead to an error), I chose the more straight-forward solution and start from an empty rather than a sparse keymap and added the `digit-argument` bindings for 0..9 explicitly.

Simplify mu4e-view-mode-map creation and fix `-` binding

---

mu4e/mu4e-headers.el

The variable `mu4e-headers-from-or-to-prefix` was not defined nor used, contrarily to what the documentation says.  (I like to customize the prefix to a non-textual symbol as I find it increases legibility for me.)

Make mu4e~headers-from-or-to respect its documentation

---

mu4e/mu4e-org.el

The error can cause org-store-link to short circuit before it should (e.g. when org-store-link is called by org-babel-tangle-file).

mu4e-org-store-link: prevent error when no message at point

---

guile/meson.build
guile/mu-guile-message.cc
mu4e/mu4e-view.el

Previously, the cursor would be moved to the first html attachment which
would break using mu4e keybindings (e.g. delete). With this change, the
cursor isn't moved at all, presumably the expected behavior.
I've targeted this for the 1.8 release branch because it seems like a bug but if
you want to apply to master instead, that's fine.

mu4e-view: use `save-excursion' around toggling html

---

mu4e/mu4e-headers.el

Sometimes fields (especially subject fields) contain disruptive characters like new lines which will mess up the mu4e-headers view. This changeset introduces `mu4e~headers-sanitize-field-value` to replace all control characters by spaces.
Note, Unicode Left to Right Overrides do not cause any problems so they are ignored.

m4e: remove disruptive characters from header fields

---

mu4e/mu4e-main.el

It always struck me as a bit odd to force the user to refresh the main
view after updating and indexing their mail. This change creates a hook
that will simply call `revert-buffer' after an indexing completes.

mu4e-main: automatically update the mail counts after indexing

---

mu4e/mu4e-view.el

If `browse-url-handlers` is set `mu4e-action-view-in-xwidget` function tries to open url in the handler first instead of xwidget. This is happening because `browse-url` first checks `browse-url-handlers` and `browse-url-browser-function` after.

mu4e: temporary reset browse-url-handlers in view in xwidget action

---

mu4e/mu4e-helpers.el

This allows one to copy the link behind a link-widget instead of using RET to open it.
I've been having good success with this patch on my system for the last several days. It's very handy -- I currently cannot open links directly into a browser with my setup.

Teach mu4e-copy-thing-at-point about SHR links

---

mu4e/meson.build
mu4e/mu4e-compose.el
mu4e/mu4e-draft.el
mu4e/mu4e-headers.el
mu4e/mu4e-helpers.el
mu4e/mu4e-icalendar.el
mu4e/mu4e-main.el
mu4e/mu4e-mark.el
mu4e/mu4e-message.el
mu4e/mu4e-update.el
mu4e/mu4e-vars.el
mu4e/mu4e-view.el
mu4e/mu4e-window.el
mu4e/mu4e.el
mu4e/mu4e.texi

Hi Dirk-Jan,
Phew. OK, so, this (sadly rather large) PR fixes a large number of long-standing issues and standardises buffer display so it uses Emacs's `display-buffer`, `pop-to-buffer`, and action system so users can override everything in `display-buffer-alist`.
Here's what it does:
1. Separate (all, I think!) window and buffer management into `mu4e-window.el`;
2. Centralise the creation and retrieval of headers and view buffer into two functions;
3. Centralise the display of buffers to `mu4e-display-buffer`;
4. Rewrite all split window code to use `display-buffer` and the action display system;
5. Support multiple, distinct and standalone headers and views. Views are now detachable (`z` key) from a header, meaning it is inviolable and not touched by movement and navigation elsewhere. …

Multiple buffer support and standardised window and buffer handling

---

mu4e/mu4e-folders.el

"/" was hardcoded as initial input to `mu4e-completing-read-function' when selecting 'other' maildirs. This can now be set by the user.

Add variable for initial input to maildir selection

---

mu4e/mu4e-headers.el

Triggering a search -- directly, or indirectly through reindexing -- calls `mu4e-headers-mode` which kills all buffer-local variables including `mu4e~headers-view-win`, which causes any live view windows to lose their 'connection' to the now-updated headers buffer.

Preserve `mu4e~headers-view-win' when a search is (re-)executed

---

mu4e/mu4e-view.el

It just occurred to me that my bug-reference setup didn't work anymore with the
current master.  I activate `bug-reference-mode` in `mu4e-view-mode-hook`.  That
doesn't work anymore because the mode is activated now when the buffer is still
empty.  It works again when activating in `mu4e-after-view-message-hook`.  So I
added a clarifying comment.
Also I've made the headers whose values are checked to figure out a suitable
bug-reference setup a variable and added Reply-To there.
Well, I guess I'm the only user of that feature anyway... ;-)

bug-reference: Add clarifying comment / checked-headers as variable

---

mu4e/mu4e-main.el
mu4e/mu4e-window.el

Fixes #2382 by making `*mu4e-main*` use `display-buffer` actions to prefer a full frame.

Change how *mu4e-main* is displayed and default to full frame

---

mu4e/mu4e-folders.el
mu4e/mu4e-main.el
mu4e/mu4e.texi

1. Add a `:name` attribute to `mu4e-maildir-shortcuts` to display maildirs with long paths nicely
2. Add support for maildir shortcuts without a `:key`. Alternatively, allow `:key` to be a custom string.
I find a custom string useful for hinting at hydras.
This implements [#2110], which has conflicts with the current code.
I also added support for separator lines with titles to categorizes maildirs. Something like
```
* -- Private --
* [jp]  /private/inbox                                         (n/N)
* -- Work --
* [jw]  /work/inbox                                            (n/N)
```
I didn't include it since it's quite hackish, but I'd be prepared to clean it up and submit it if interested.
Sorry for opening/closing two other pull requests. I'm not too used to the Github workflow :)

More customizable maildir shortcuts

---

mu4e/mu4e-view.el

Don’t delete the existing buffer window when viewing a new message when `mu4e-split-view` is `single-window` or `nil`. This was causing the window layout to be trashed when navigating to a new message with `n` or `p` with a message open when in single-window mode.

mu4e-view: don't delete window on view msg in single-window mode

---

mu/mu-options.cc

I use mu on a resource constrained VPS, so I need to reduce batch-size from the default value, thus I found this bug.

fix batch-size option in sub_init

---

mu4e/mu4e-folders.el

* mu4e/mu4e-folders.el: Correct few docstrings
(mu4e-get-drafts-folder): Fix docstring
(mu4e-get-trash-folder): Fix docstring

Correct 2 docstrings in mu4e-folders.el

---

lib/utils/mu-error.hh

GCC 13s libstdc++ reduced its dependency on some headers like <cstdint>, so it's no longer transitively included through various headers.  Include it explicitly.
See also: https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes
```
../lib/utils/mu-error.hh:36:26: error: ‘uint32_t’ does not name a type
36 |         static constexpr uint32_t SoftError = 1 << 23;
|                          ^~~~~~~~
```

mu-error: Add missing <cstdint> include

---

lib/mu-server.cc

Without this patch, I see the following error:
```
;; mu> (move :docid 1 :maildir "/.Archive")
[2b](:error 32818 :message "invalid flags ''")
```
flags should not default to "", which is not a valid flags string.

really allow flags to be empty in move command

---

mu4e/mu4e-folders.el

This patch allows mu4e to autocomplete when `mu4e-root-maildor` contains symbolic links to other maildirs. Without this patch mu4e can still work when directories under `mu4e-root-maildor` are symlinks, but it will not autocomplete properly when using `mu4e-search-maildir`.
Signed-off-by: Andreas Hindborg <nmi@metaspace.dk>

mu4e: Allow completion for symbolic links in maildir

---

mu4e/mu4e-view.el

This PR aims to improve the support for bug-reference-mode introduced in #2021.
Currently, we might call `add-hook` on `bug-reference-auto-setup-functions` before `bug-reference` is loaded, which results in overriding the default value. I think it makes much more sense to add our hook to the list of hooks, which is what this PR aims to achieve.
@tsdh You might be interested in this change.

Only add bug-reference setup function after the feature was loaded

---

mu4e/mu4e.texi

s/%d:date-timestamp-inactive/%:date-timestamp-inactive

typo in mu4e docs Org-mode links

---

mu4e/mu4e-main.el

Otherwise, if ALT is not provided the initial binding of bindstr can fail with: Wrong type argument: characterp, nil

mu4e--main-action: guard against nil ALT argument

---

mu4e/mu4e-org.el

This change makes it possible to use the function in an mu4e action, like so:
```
(defun jjh/mu4e-action-store-and-capture (msg)
"Store the link to MSG, then run `org-capture'."
(mu4e--org-store-link-message msg)
(org-capture))
```

mu4e: Add optional message plist arg to mu4e--org-store-link-message

---

mu4e/mu4e-view.el

If the headers buffer isn't in a live window (e.g., mu4e-split-view is 'single-window), get-buffer-window will return nil. In turn, with-selected-window will die if fed a nil window, so default to using the current window in this case.
This fixes a regression from c23dad70586bbb54891c506629f2ce2ed8e463d2 that prevented using n/p from a view buffer.

Don't die if the headers buffer isn't in a window

---

mu4e/mu4e-headers.el
mu4e/mu4e.texi

Fixed an issue where messages from mailing-list ("list" flag) were shown using "s" in header view, which is also used for "signed" messages. Therefore changing it to "L".

Change letter mark for mailing-list messages to "L"

---

mu4e/mu4e-draft.el
mu4e/mu4e-folders.el
mu4e/mu4e-helpers.el
mu4e/mu4e-query-items.el
mu4e/mu4e-search.el
mu4e/mu4e-server.el
mu4e/mu4e-view.el

So that the type definitions reflects the docstrings more closely.  In additon, fixed warnings from flymake about docstring.
* mu4e/mu4e-draft.el mu4e-compose-keep-self-cc: should be a comma
* mu4e/mu4e-folders.el mu4e-maildir-shortcuts: recognize new (plist) format
* mu4e/mu4e-helpers.el mu4e-debug: removed unnecessary double space in docstring
* mu4e/mu4e-query-items.el mu4e-query-rewrite-function: prepend "\\=" before column 0 "(" in docstring
* mu4e/mu4e-search.el mu4e-search-sort-field mu4e-search-sort-direction: used radio in types
* mu4e/mu4e-server.el mu4e-mu-binary: "mu" executable must exist
* mu4e/mu4e-view.el mu4e-view-fields: fixed type
mu4e-view-actions: for function refs, prefer "#'" rather than "'"

Fix defcustom type definitions

---

mu4e/mu4e.texi

A one word change to documentation: 
"place it in a new *tab* by typing C-x w ^ f"  -> "place it in a new *frame* by typing C-x w ^ f"

documentation typo: C-x w ^f places in new frame, not new tab

---

mu4e/mu4e-view.el
mu4e/mu4e.texi

Without creating some kind of a temporary name (which could then be
trivially renamed by the user as the current instructions say) a new
user trying to learn how to detach a view will run into this error when
switching to a new message after detaching:
[mu4e] Detached view buffer from *mu4e-headers*
funcall-interactively: No buffer named *mu4e-article*<2>
It seems like a good default and less friction to create a random name
automatically when detaching.

[ux bug] mu4e: create random name for newly detached views

---

mu4e/mu4e-modeline.el
mu4e/mu4e.texi

This patch permits configuring mu4e so only buffer-specific modelines are displayed.
Contrary to the solution I initially suggested in <https://github.com/djcb/mu/issues/2463>, not registering the modeline is not enough. This is because somebody could have `mu4e-modeline-show-global` set to `t`, start `mu4e` (the global modeline is registered), then set it to `nil` and re-start `mu4e`. As there's nothing cleaning up `mu4e--modeline-global-items`, changing `mu4e-modeline-show-global` during an Emacs session that followed the path described wouldn't work.
The new way of fixing this is more resilient, allowing the global modeline to be registered but only adding the global bits to the return value of `mu4e--modeline-string` when configured to do so. This approach allows as well changing …

mu4e: allow to disable the global mode-line items

---

mu4e/mu4e-thread.el

mu4e-thread.el is a small file that allows to fold and unfold threads in mu4e headers mode. Folding works by creating an overlay over thread children that display a summary (number of hidden messages and possibly number of unread messages). Folding is perform just in time such that it is quite fast to fold/unfold threads. When a thread has unread messages, the folding stops at the first unread message unless `mu4e-thread-fold-unread` has been set to t.
Similarly, when a thread has marked messages, the folding stops at the first marked message and it is strongly advised to disable marking on folded messages as explained in usage example.

Added mu4e-thread.el

---

mu4e/mu4e-headers.el

This was run outside of the `with-current-buffer (mu4e-get-headers-buffer)` in `mu4e~headers-found-handler`, which could be anywhere.
I noticed it when `mu4e-thread-mode` was suddenly active in other buffers and shadowed my `C-tab` binding.

Ensure mu4e-thread-mode is only enabled in headers buffer

---

mu4e/mu4e-contacts.el

* mu4e/mu4e-contacts.el
(mu4e-personal-address-p): Fix docstring error (return nil *only if* the address does not match any of the personal addresses, not the other way around).  Unwrap unnecessary (if COND t nil) to just COND because its caller `seq-find` only distinguishes between nil and non-nil.
(mu4e-personal-address): Add space in defun between name and args. Ensure double space after a sentence ends.  Convert a duplicated call of (mu4e-server-properties) into using when-let and reusing its result.

Updates to mu4e-contacts.el

---

mu4e/mu4e-draft.el
mu4e/mu4e-thread.el

* mu4e/mu4e-draft.el (mu4e-compose-reply-recipients): (mu4e-compose-reply-to-address):
* mu4e/mu4e-thread.el (mu4e-thread-fold-single-children): Clarify docstrings and fixed type definitions.
(Wrote a command that checks types for all options in a group, so all types should be good now.)

Fix more defcustom type errors and reworded docs

---

mu4e/mu4e-folders.el

Some packages like `vertico-prescient` adding text-property to vertico candidates will break `mu4e-ask-maildir` response.
Here is the screenshot when text-property candidates caused error:

Fix asking maildir reading completing candidate is text-property

---

mu4e/mu4e-contacts.el

Should `mu4e-compose-complete-max` take a string or integer?  I can't deduce it from the docs.

* mu4e/mu4e-contacts.el (mu4e-compose-complete-max): fix type

---

mu4e/mu4e-notification.el

This PR adds a default notification action.
This is what the freedesktop.org specification says:
>  The default action (usually invoked by clicking the notification) should have a key named "default". The name can be anything, though implementations are free not to display it.

mu4e-notifications: add default action

---

mu4e/mu4e-draft.el

Fixes https://github.com/djcb/mu/issues/2535

Don't use the original message `To` for a reply `To` field

---

man/exit-code.inc
man/mu-easy.7.org
man/mu-query.7.org
man/mu-view.1.org
man/mu.1.org

Fixes for a spelling mistake, a few formatting typo's and an incorrectly rendered form-feed escape-sequence.

Man page fixes

---

meson.build
mu4e/meson.build
mu4e/mu4e-config.el.in
mu4e/mu4e-pkg.el.in

`mu4e` does not conform with `pakcage.el`, which makes autoload commands, such as `(mu4e)`, not work.  Users have to `(require 'mu4e)` first.
`(package-activate-all)` of `package.el` is responsible for loading `NAME-autoloads.el` of all packages when Emacs starts.  See `(elisp) Startup Summary`.
- The default installation dir does not conform with `package.el`.  `package.el` looks for packages in `package-user-dir` and `package-directory-list`.  Check the source of `package-load-all-descriptors`.
- Missing `mu4e-pkg.el` description file.  See https://www.gnu.org/software/emacs/manual/html_node/elisp/Multi_002dfile-Packages.html.
- Missing `mu4e-autoloads.el`.  If a package is installed using `package.el`, this file will be generated.  Since we do not use `package.el` to install `mu4e`, we …

mu4e: make it conform with `package.el`

---

mu4e/mu4e-headers.el

Brings visual consistency to unfolded threads.

mu4e: propertize thread prefix characters

---

mu4e/mu4e-update.el

This buffer is not intended to be edited.
Special mode also allows quickly dismissing via the quit-window binding.

mu4e: use special-mode for mu4e-last-update-buffer

---

mu4e/mu4e-mark.el

The `const` values of the choice had the wrong order `(const :tag <value> <text>)`.
The correct order is `(const :tag <text> <value>)`.
This resulted in the following warning when loading mu4e:
```
⛔ Warning (emacs): Value ‘apply’ does not match type (choice (const :tag ask ask user whether to ignore marks) (const :tag apply apply marks without asking) (const :tag ignore ignore marks without asking))
```

Fix defcustom :type of mu4e-headers-leave-behavior

---

mu4e/mu4e-compose.el
mu4e/mu4e-contrib.el

An argument was missing in the callback defined in `mu4e-compose-mail`.

Fix mu4e-compose-mail and some warnings

---

mu4e/mu4e-actions.el

Sets the second parameter to `replace-match' to t, thus forcing it to not attempt to auto-adjust the case of any tags.
Addresses #2574 .

When re-tagging, force `replace-match' to preserve case

---

mu4e/mu4e-compose.el

Previous assertion would fail when REPLY-TYPE is nil, but nil is a valid value for the argument.
See: https://github.com/djcb/mu/issues/2601

mu4e-compose-reply: account for nil REPLY-TYPE in assertion

---

mu4e/mu4e-notification.el

Add support for alert.el to be used on systems that don't have native dbus functionality.
Question: is this something that can be applied to the 1.10 branch?
IMHO, this should be on 1.10 just to make 1.10 the release "where notifications work by default." Apologies for not catching this sooner.

mu4e: add support for macOS notifications

---

mu4e/mu4e-icalendar.el

I did additional tests and this is the only problem I found.
Fixes https://github.com/djcb/mu/issues/2583.

mu4e-icalendar: Fix getting the organizer from the message

---

meson.build
meson_options.txt

Add an option for builders to explicitly disable cld2, instead of relying on the automatic detection.

build: add cld2 option

---

man/meson.build
man/mu-add.1.org
man/mu-bookmarks.5.org
man/mu-cfind.1.org
man/mu-easy.7.org
man/mu-extract.1.org
man/mu-find.1.org
man/mu-help.1.org
man/mu-index.1.org
man/mu-info.1.org
man/mu-init.1.org
man/mu-mkdir.1.org
man/mu-move.1.org
man/mu-query.7.org
man/mu-remove.1.org
man/mu-server.1.org
man/mu-verify.1.org
man/mu-view.1.org
man/mu.1.org

Fixes for some warnings and formatting errors

More man page fixes

---

guile/tests/meson.build

When meson is run in a build path that is different from source root, the generated shared library cannot be found under "<source_root>/guile".  This patch adds the corresponding path under build root to guile_root_path so that they continue to work.
This should fix https://github.com/djcb/mu/issues/2631.

Fix guile_load_path to include build path

---

mu4e/mu4e-view.el

The function 'gnus-summary-bookmark-make-record' does not work properly with the
faux "appeasement" summary buffer, causing undesired changes in the window
configuration when the message rendering buffer's bookmark function is
called (which some packages, like Activities, Burly, and Dogears do routinely).
See <https://github.com/alphapapa/activities.el/issues/55>.
Reported-by: Daniel Goldin <https://github.com/danielgoldin>

mu4e--view-render-buffer: Disable Gnus bookmark-make-record-function

---

man/mu-query.7.org

The asterisks at the beginning of these lines in this example block look like headings to Org; they need to be escaped with commas.

man: Escape Org heading-like lines in example

---

lib/utils/mu-utils.hh

In musl, `stdout` is a macro that expands to `(stdout)`, and `::(stdout)` is not valid C++.
```
../mu-1.12.2/lib/utils/mu-utils.hh:268:32: error: expected id-expression before '(' token
268 |                              ::stdout);
|                                ^~~~~~
```
Nothing in the Mu namespace is named stdout, so it is safe to drop the `::`.
Bug: https://bugs.gentoo.org/928361

mu-utils: Fix build with musl

---

mu/mu-cmd-move.cc

The `mu move` command always prints messages to `stderr` which seem like they were left over from some debugging session. These are hard to filter out without also potentially suppressing error messages. They're also present when giving the `--quiet` option. I don't think these serve any purpose at the moment, so I suggest to just remove them.

mu-move: remove debug print

---

lib/mu-scanner.cc

According to the readdir(2) man-page, not all file-systems support returning the entry's file-type in `d_type`.  For example, the reprotest reproducibility tool, uses the disorderfs FUSE file-system to shuffle the order in which directory entries are returned, and this does not set `d_type`.  Therefore, in addition to entries with type `DT_DIR` and `DT_LNK`, also process entries with type `DT_UNKNOWN`.
For example, install disorderfs:
Mount mu over it:
$ mkdir mu-disordered
$ disorderfs mu mu-disordered
disorderfs: reversing directory entries
Build mu:
$ cd mu-disordered/
$ meson setup build .
The Meson build system
Version: 1.4.0
Source dir: /space/azazel/work/git/repos/github/a3a3el/mu-disordered
Build dir: /space/azazel/work/git/repos/github/a3a3el/mu-disordered/build
Build type: …

scanner: don't skip directory entries with type `DT_UNKNOWN`

---

mu4e/mu4e.texi

I think I found two typos in the Mu4e Info manual. Here is a fix.

Mu4e info manual typos fix

---

man/mu.1.org

I think I found a couple errors in the main `mu` manual page. Here is a fix.

Man typos fix

---

mu4e/mu4e-search.el

For some reason (probably because I don't use it so often), I forget how to toggle the search properties.  Adding a menu entry makes it easier to (re)discover.

Make toggling search properties easier to discover

---

mu/mu-options.cc

Hey,
when I tried to set up `mu` I ran into the following issue:
I ran `mu init --maildir ~/mail` which worked fine but when I tried to do `mu index`
no mails where found. After some investigating I noticed `mu` stores my maildir as `/home/USER//mail` but then disregards mails with the canonical path `/home/USER/mail/...` because they don't have this exact prefix.
I thought it would make sense to store the maildir (which is already ensured to be absolute) as canonical path too and therefore canonicalize the `mu init --maildir` argument after expanding.
This fixes my problem, I hope it doesn't break something else. Feedback is appreciated. :)

Canonicalize init --maildir argument after expanding

---

lib/mu-store-worker.hh

Fix gcc warning:
```
mu4e                           pre-build              [26/198] Compiling C++ object lib/libmu.a.p/mu-query-parser.cc.o               34.390111
mu4e                           pre-build              In file included from ../lib/mu-store.hh:34,                                   34.390132
mu4e                           pre-build                               from ../lib/mu-query-parser.hh:25,                            34.390140
mu4e                           pre-build                               from ../lib/mu-query-parser.cc:20:                            34.390146
mu4e                           pre-build              ../lib/mu-store-worker.hh:162:23: warning: extra ‘;’ [-Wpedantic]              34.390152
mu4e                           pre-build                162 | …
```

Update mu-store-worker.hh, remove duplicate `;`

---

lib/utils/mu-utils.cc

In Mu::parse_date_time, when provided with an empty string, return time_t_max instead of G_MAXINT64. For systems with a 64-bit time_t, there is no difference. With a 32-bit time_t it caused a test to fail:
not ok /utils/date-basic - ERROR:../mu-1.12.4/lib/utils/tests/test-utils.cc:92
void test_date_basic(): assertion failed
(parse_date_time(std::get<0>(test), std::get<1>(test)).value_or(-1)
== std::get<2>(test)): (18446744073709551615 == 2147483647)
This edge case probably only affected the test, as when other parts of the application call parse_date_time (e.g. mu-server.cc and mu-query-processor.cc), they check if the input string is empty first.

lib: use time_t_max for empty datetime

---

mu4e/mu4e-draft.el

* Set `message-newsreader' before calling `mu4e--prepare-draft-buffer' so that `User-Agent' is properly set.
* Fixes #2750.
(Though I'm not very certain this is the best place to set this.  Please advice.)

Ensure `User-Agent' is set

---

man/meson.build

The zero-width spaces are added by the `man-link` macro to ensure bold text formatting when exporting from org, but they interfere with man page functionality in Emacs.
Fixes https://github.com/djcb/mu/issues/2753. Let me know if you'd like the comment to be more/less wordy.

Replace zero-width spaces in man pages with an empty string.

---

man/mu-query.7.org

Update mu-query man page to point to the mu info fields command.

Correct mu-query man page

---

mu4e/mu4e-server.el

Noticed documentation related typos while inspecting the function mu4e--server-move.

doc(mu4e--server-move): typos

---

mu4e/mu4e-actions.el

Somehow, empty tags creep into the tag list; so now `, tag1, tag2` becomes `tag1, tag2`.

mu4e-actions: ensure empty tag removal on message retagging.

---

mu4e/mu4e-org.el

With this change, mu4e: links now load mu4e if it wasn't loaded already.

mu4e-org: autoload org-link-set-parameters

---

mu4e/mu4e.texi

`(add-hook 'mu4e-thread-mode-hook #'mu4e-thread-fold-apply-all)` doesn't seem to fold threads. Did you mean `(add-hook 'mu4e-thread-mode-hook #'mu4e-thread-fold-all)`?

Fix a potentially misnamed function

---

mu4e/mu4e-compose.el

`mu4e-compose-post-trigger` does not exist.

mu4e-compose: fix docstring

---

mu4e/mu4e.el

This change turns the mu4e refresh timer into a named function, making M-x list-timers output display a name having to do with mu4e instead of an inscrutable "anonymous lambda" line.

Use named function, not lambda, for refresh timer

---

man/mu-query.7.org

Commit 721aadc140f2 ("man: change quoting style") replaced single-quoted strings of the form:
'lorem ipsum'
with:
`lorem ipsum'
to prevent the possibility of single quotes appearing at the beginning of lines, because these will be misinterpreted by troff.  However, changes to the man-page sources in 1.12.9 reintroduced some of these, including one which does appear at the beginning of a line in mu-query(7):
'"', '*', '(' and ')'. The details are shell-specific. In case of doubt, the
which results in the following warning:
troff:<standard input>:25: warning: macro '"',' not defined
and the omission of that line from the rendered paragraph:
NOTE:  if  you  use  queries on the command-line (say, for mu find), you
need to quote any characters that would otherwise be interpreted by  the
shell, …

man: fix some single-quoted strings

---

lib/mu-server.cc

improve the performace of indexer with exponential backoff for doubling sleep duration.
I already tested it on my own Linux box. For a small maildir it will significantly improve the user experience.

indexer sleep exp backoff
