djcb/mu

- mu4e/mu4e.texi
PR as requested in https://github.com/djcb/mu/issues/569
> Add FAQ on how to activate format=flowed

- mu4e/mu4e-main.el
These 2 shortcuts update mail index in both the headers and view modes
but not in the main view.
> Make sure C-S-u and C-c C-u work in main view

- mu4e/mu4e-headers.el
This allows for a key binding to something like:
(mu4e-headers-mark-thread-using-markpair '(read))
> Extract mu4e-headers-mark-thread-using-markpair

- mu4e/mu4e-view.el
There was a discussion at the `mu-discuss` Google group about [How to easily save all attachments?](https://groups.google.com/d/topic/mu-discuss/LpwtWZ1WCyg/discussion).
I have added an option to allow saving all attachments into the same directory when using `C-u e`. By default this option is deactivated to not mess with existing workflows.
As I'm a complete Elisp newbie it would be great if you could give me some hints to improve the code in case there's something wrong with my implementation.
> Add option for saving multiple attachments into same directory.

- mu4e/mu4e.texi
Here is some basic documentation for BBDB. I'll come back to it once there is an official release of BBDB with the mu4e integration.
> #621 BBDB documentation

- mu4e/mu4e-view.el
A fix of the underlying issue would of course be preferable but my understanding of mu4e is not good enough for that.
> mu4e: Added workaround for #417.

- ChangeLog
Not all ChangeLogs are useless. =)
> Point ChangeLog to actual change log

- NEWS.org
> Fix version numbers

- lib/mu-flags.h
- lib/mu-index.c
- lib/mu-msg-fields.c
- lib/mu-msg-fields.h
- lib/mu-store-write.cc
- lib/mu-str.c
I separated minor fixes from #666. They might be still useful and now are easy to merge.
> Minor whitespace and comment fixes

- mu4e/mu4e.texi
> Mention how to shorten list names with dots

- NEWS.org
- README.org
- mu4e/mu4e-about.org
- Walked through the NEWS, README, and about org-pages and removed some
white spaces that where sticking around.
- :metal:
> Cleaned up some trailing white space(s)

- mu4e/mu4e-headers.el
Hi @djcb!
I'm starting to like mu4e a lot :) It's really nice. I've been playing around with the code a bit, attempting to understand a few things. While doing so, I noticed two small issues in the header list:
* Header lines always have a trailing space
* Header lines are constructed by repeated concatenation
This PR fixes these two issue by slightly refactoring the `header-handler` function. It also implements two more small changes:
* I removed the `(when str` check. It probably should be added again, but I don't really understand its purpose. In the original code, if `str` is nil, then all subsequent fields will be improperly aligned, won't they?
* I changed `propertize` to `add-face-text-property`, which works in place instead of making a copy, and does not erase the existing faces …
> Refactor mu4e~headers-header-handler

- mu4e/mu4e-headers.el
Menu items for threading and include-related in header view.
> Mu4e: Added missing menu items.

- lib/mu-msg-part.c
- lib/mu-msg-part.h
- lib/mu-msg-sexp.c
- mu4e/mu4e-actions.el
- mu4e/mu4e-utils.el
This will make view in browse works with attached images
> Handle attached images when write msg body to html

- mu4e/mu4e.texi
Fixes https://github.com/djcb/mu/issues/843
But not the only possible way out — please comment.
> Improve the description of C-c C-k in compose mode

- lib/mu-msg-part.c
Improve the function ``cleanup_filename()`` of ``lib/mu-msg-part.c`` to use Unicode characters when replacing the control characters, slashes and colons with ``-``.
Originally, this function just use plain C characters (i.e., assuming ASCII string) when checking each character is or not a control character, slash or colon.  However, when the attachment filename contains non-ASCII (e.g., Chinese characters), all the non-ASCII characters are replaced with ``-``.
For example:
* Before:
```
> mu view test_chinese_attachment_filename.eml
From: Tester <tester@example.com>
To: Example <example@example.com>
Subject: Test email with attachment of Chinese filename
Date: Mon 23 May 2016 05:22:09 PM CST
Attachments: 'attachment-test.txt', '------------.txt', '-------test.txt'
Hello,
This is a simple …
```
> Use Unicode characters when cleaning up attachment filename

- mu4e/mu4e-compose.el
* mu4e/mu4e-compose.el (mu4e~compose-handler):
Save and restore window config.
> Fix window restoration when C-g'ing on reply.

- mu4e/mu4e-view.el
Press `TAB` within header field key to toggle
> mu4e: Allow header fields with more than one lines to fold to one

- mu4e/mu4e-actions.el
This adds a variable mu4e-action-tags-completion-list, that contains a list of commonly used tags to suggest as completion terms during a retag actions.
Along the way, the retag action accepts as argument a comma-separated list of +tag and -tag keywords, instead of a space-separated one, removing the need to quote tags with spaces in them, and making it consistent with the behaviour of completing-read-multiple.
> add rudimentary completion support for retag action

- mu4e/mu4e-contrib.el
- mu4e/mu4e-utils.el
Another way to attach files that I find useful.
> Adding eshell/mu4e-attach allowing attachments from eshell.

- mu4e/org-mu4e.el
> Only call old org-link API if new unavailable

- mu4e/mu4e-compose.el
- mu4e/mu4e-headers.el
- mu4e/mu4e-main.el
- mu4e/mu4e-view.el
> Don't erase global-mode-string with context label, but add to it

- mu4e/mu4e-context.el
This is useful if you change e.g. bookmarks in the context vars and want your menu to reflect that.
Would this be an acceptable alternative to https://github.com/djcb/mu/pull/960?
> mu4e: redraw menu after context switch

- mu4e/mu4e-view.el
* mu4e/mu4e-view.el (mu4e-view-attachment-action):
Handle multi save in mu4e-view-attachment-action.
* mu4e/mu4e-view.el (mu4e-view-attachment-actions):
Make mu4e-view-attachment-actions a defcustom and add some options.
New user variable mu4e-view-attachment-assoc.
* mu4e/mu4e-view.el (mu4e-view-attachment-assoc): New.
(mu4e-view-open-attachment-with): Use it.
> Add some improvements in attachment actions.

- mu4e/mu4e-utils.el
This is the fix for #989 as requested.
> Use re-search-forward to find message signatures 

- mu4e/mu4e-headers.el
- mu4e/mu4e-view.el
> mu4e: Added menu items for untrash

- mu4e/mu4e.texi
Inspired by this mu-discuss thread:
https://groups.google.com/d/msg/mu-discuss/rAT2YJPEwsA/eYmoGJbUCgAJ
> Add example of matching maildir and its sub-directories in contexts

- mu4e/mu4e.texi
Hi,
The previous link didn't exist. 
So I updated it!
Cheers,
Damien
> mu4e: update the org-contacts package link in the doc

- mu4e/mu4e-compose.el
> Fix typo in mu4e-sent-messages-behavior docs

- mu4e/mu4e-view.el
> Revert "Ensure mu4e-view-mode-hook run after text insertion"

- mu4e/mu4e-lists.el
Kind of self-explanatory I hope!
> Use defcustom for the customizable variables in mu4e-lists.el

- mu4e/mu4e-actions.el
A couple of tweaks to make patch application better.
> Patch application updates

- HACKING
Had to install libtool. I'm on Ubuntu 18.04
> Add Ubuntu dependency

- mu4e/mu4e-message.el
> Non-breaking spaces should be replaced with a space and not removed

- mu4e/mu4e-view.el
Before this change, I would press "o" and `mu4e~view-attach-map' would
be nil. Now it works as expected.
> mu4e/mu4e-view.el (mu4e-view-open-attachment): Ensure attachments are set

- lib/mu-query.cc
The current threading algorithm is applied to the entire result of a query, even
if maxnum is specified, and then the result of the threading algorithm is
truncated to maxnum. The improves threading results by returning the entire
thread even when only a single message makes it into the top maxnum results.
This commit applies the threading algorithm to the related message set of the
maxnum-truncated query result instead of to the entire query result. For a given
set of messages, the set of messages which will share threads with any of the
original messages is exactly the related message sets. Put another way, either
any messages returned by the original query but removed by the maxnum truncation
will also be returned by the related message query, or they would not have been
needed anyway …
> Perform threading calculation on related set instead of entire result.

- mu4e/mu4e-compose.el
Fixes https://github.com/djcb/mu/issues/1358
> Set mml-enable-flowed according to mu4e-compose-format-flowed

- mu4e/mu4e-context.el
- mu4e/mu4e-headers.el
- mu4e/mu4e-view.el
- mu4e/mu4e.texi
> Easy accounts with make-mu4e-context-account

- mu4e/mu4e-actions.el
- mu4e/mu4e-context.el
- mu4e/mu4e-contrib.el
- mu4e/mu4e-draft.el
- mu4e/mu4e-icalendar.el
- mu4e/mu4e-lists.el
- mu4e/mu4e-mark.el
- mu4e/mu4e-message.el
- mu4e/mu4e-proc.el
- mu4e/mu4e-speedbar.el
- mu4e/mu4e-vars.el
- mu4e/mu4e.el
- mu4e/org-mu4e.el
- mu4e/org-old-mu4e.el
about free variables (declare) and unused lexical vars (prefix with "_").
> Add lexical-binding to all files and fix warnings

- lib/mu-msg-part.c
> Treat text/markdown as plain text for issue #1503

- mu4e/mu4e-vars.el
let custom-set-variables work.
> mu4e: remove duplicated mu4e-bookmarks define

- mu4e/mu4e-context.el
- mu4e/mu4e-contrib.el
- mu4e/mu4e-icalendar.el
- mu4e/mu4e-utils.el
* mu4e/mu4e-context.el (mu4e-context-switch):         Do it.
* mu4e/mu4e-contrib.el (mu4e-view-mode-hook):         Do it.
(mu4e-headers-mode-hook):                             Do it.
* mu4e/mu4e-icalendar.el (mu4e-icalendar-reply-ical): Do it.
* mu4e/mu4e-utils.el (mu4e~start):                    Do it.
(mu4e-split-ranges-to-numbers):                       Do it.
> Unquote lambda's

- mu4e/mu4e-main.el
* mu4e/mu4e-main.el (mu4e~main-bookmarks): Do it.
> Rewrite mu4e~main-bookmarks to have bookmarks aligned

- mu4e/mu4e-view.el
Thanks for merging the code to be able to add additional fields in Gnus view.  This PR fixes a duplicate variable.
> mu4e-view: (gnus) Remove duplicate bound variable

- .gitignore
- lib/mu-store.cc
- mu/mu-cmd-server.cc
> error fix for msys+gcc9.1.0

- mu4e/mu4e-view.el
> Unquoted mu4e-view-use-gnus in unless form

- mu4e/mu4e-view.el
Fixes https://github.com/djcb/mu/issues/1625
> Fix displaying ical attachments with no charset

- .gitignore
- m4/host-cpu-c-abi.m4
Add an apparently missing m4 file from gnulib, and improve the .gitignore state of the m4/ subdirectory.
> Fix autoreconf

- mu4e/mu4e.texi
> typo in mu4e.texi

- lib/mu-container.c
- mu/test-mu-threads.c
My fix for https://github.com/djcb/mu/issues/1657
> mu: always sort descending within threads

- README.org
Added svg icon to README
@djcb See:
https://github.com/damon-kwok/mu/tree/svg
> Added svg icon to README

- mu4e/mu4e.texi
Fixes https://github.com/djcb/mu/issues/1825
> Add a section about iCalendar to the manual

- mu4e/mu4e.texi
> Ical documentation

- lib/mu-maildir.c
I was originally looking at this code because clang was producing an alignment warning in `dirent_new`, but once I took a look I realized this code can be simplified a lot. Usage of `readdir_r(3)` is discouraged according to the [glibc docs](https://www.gnu.org/software/libc/manual/html_node/Reading_002fClosing-Directory.html), which explain the problems with `readdir_r(3)` better than I can here. There's an even more detailed explanation of the issue [in this blog post](https://elliotth.blogspot.com/2012/10/how-not-to-use-readdirr3.html). Basically all modern implementations of libc use a pointer to data within the `DIR*` handle for the return value of `readdir(3)` (including on bsd/macos), so as long as that `DIR*` handle isn't used my multiple threads concurrently there aren't thread …
> Use readdir(3) instead of deprecated readdir_r(3) in mu-maildir.c

- mu4e/mu4e-view.el
in replacement of mu4e-view-save-attachment-multi for gnus viewers.
The alias mu4e-view-save-attachment have been replaced by a wrapper function
that calls either mu4e-view-save-attachment-multi or
mu4e-view-gnus-save-mime-parts depending of the context.
> Fix #1790 by providing mu4e-view-gnus-save-mime-parts

- mu4e/mu4e-view.el
Fixes https://github.com/djcb/mu/issues/1842
> Restore C-h b default behavior

- mu4e/mu4e-view.el
Followup on https://github.com/djcb/mu/issues/1823
Fixes https://github.com/djcb/mu/issues/1886
> Fix the decoding of accents in Gnus view

- mu4e/mu4e-view-common.el
> Fix mu4e-view-common header line

- mu4e/mu4e.texi
Document  `mu4e-view-blocked-images'.
> mu4e/doc: Describe `mu4e-view-blocked-images'

- mu4e/mu4e-headers.el
Fixes https://github.com/djcb/mu/issues/1977
> mu4e-headers: Set the point in the correct frame after search

- mu4e/mu4e-view-gnus.el
> Insert text without its text properties when replying

- lib/mu-query-threads.cc
Even if a container has no query_match, it may still have children that need to
have flags applied.
This was broken by 6ff9829ce1e57e9f7fb4933d1389f4fd81dbd5dc.
Fixes: #1995
> threads: fix flag handling of orphan children

- mu4e/mu4e-utils.el
The bug-reference mode in Emacs 28 has support for several kinds of auto-setup, one of them being for mail customizable by the variable `bug-reference-setup-from-mail-alist`.  Add mu4e support for that so that users can simply do
``` emacs-lisp
(add-hook 'mu4e-view-mode-hook #'bug-reference-mode)
```
and have it working.
Also squash one byte-compiler warning about the (at compile-time) undefined variable `gnus-article-buffer`.
> Add support for bug-reference auto-setup in mu4e-view-mode

- mu/mu-config.cc
Looks like a copy/paste error.
> fix wrong configuration key reference

- mu4e/mu4e-headers.el
This change is needed because forward-line doesn't honor this variable, more
generally visual lines.
Using `next-line` instead of `forward-line` allows this but it is more focused
on interactive use, so use `line-move` which handles visual lines without
warnings and return 0 or 1 just like `forward-line`.
> Ensure mu4e~headers-move honor line-move-ignore-invisible

- mu4e/mu4e-view-gnus.el
> Create numbered backup of attached file when already exists #2090

- mu4e/mu4e-headers.el
When using a side-by-side split layout, i.e., headers left of message view, it
easily can happen that parts of the headers (like a longer subject) are not
visible without horizontal scrolling.  So eldoc to the rescue, which can echo a
customizable message (see `mu4e-headers-eldoc-format`) containing stuff like
subject, from, to, date, etc. in the echo area.
This PR just adds a suitable documentation function buffer-locally.  It does not enable eldoc.
> Add eldoc support in headers views

- mu4e/mu4e-view.el
Allow `mu4e-view-open-program` to be set to a function instead of a string naming some external application.  In the function case, it must be a function receiving one single argument, the filename.
> Allow a function as mu4e-view-open-program

- mu4e/mu4e-message.el
Fixes https://github.com/djcb/mu/issues/2265
> Make mu4e-message-contact-field-matches accept a list of fields

- mu4e/mu4e-headers.el
> Fix wrong cl-case usages where emacs 29 errors on byte-compilation now

- README.org
Hi, @djcb. The latest `MU` (`1.9.1`) works fine on windows. See:
```
damon.guo@Damon001 MSYS ~/MSYS2-packages/mu
$ makepkg -sf
==> Making package: mu-git 20221003-1 (Thu Oct  6 16:21:10 2022)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Cloning mu git repo...
Cloning into bare repository '/home/damon.guo/MSYS2-packages/mu/mu'...
remote: Enumerating objects: 33619, done.
remote: Counting objects: 100% (5325/5325), done.
remote: Compressing objects: 100% (1543/1543), done.
remote: Total 33619 (delta 3953), reused 5094 (delta 3772), pack-reused 28294
Receiving objects: 100% (33619/33619), 20.41 MiB | 5.92 MiB/s, done.
Resolving deltas: 100% (22333/22333), done.
==> Validating source files with sha256sums...
mu ... Skipped
==> …
```
> Added windows(MSYS2) support

- mu4e/mu4e-draft.el
> When replying to self, use :from field of original message

- mu4e/mu4e-window.el
> don't use display-buffer-reuse-window when composing in frame

- mu4e/mu4e-helpers.el
> Fix completion w other keys than quick key

- mu4e/mu4e-compose.el
> mu4e-compose-mail: fix the number of parameters of the closure

- mu4e/mu4e-compose.el
Close #2656 
Restore some code from [previous version](https://github.com/djcb/mu/blob/v1.10.8/mu4e/mu4e-compose.el#L587-L589)
> Respect `message-cite-reply-position` customization

- man/mu-index.1.org
Add a missing closing bracket.
> mu-index.1: fix typo

- mu4e/mu4e-icalendar.el
Update install instructions for icalendar. See https://github.com/djcb/mu/issues/2666
> Update install instructions for icalendar

- README.org
> fix: readme typo >> clone through ssh error

- mu4e/mu4e-headers.el
- mu4e/mu4e.texi
- Fix a menu entry
- Replace obsolete function in the doc.
> Minor improvements

- mu4e/mu4e-compose.el
> mu4e-compose: Heed shift-selection-mode for extending the selection.

- mu4e/mu4e-notification.el
I will try it for some day to see if this works correctly, I will un-draft it when I am done with my testing.
Thank you for considering this.
Closes #2833
> mu4e-notification: close notification once done

- mu4e/mu4e.texi
Noticed that this snippet doesn't work. Other than that I am a very happy new user. Thanks!
> mu4e.texi: fix smart refiling example config
